// Command helper-signatures derives checked helper metadata from the Go API.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	check := flag.Bool("check", false, "refuse stale generated signatures")
	flag.Parse()
	files, err := filepath.Glob("*.go")
	must(err)
	signatures := map[string]int{}
	for _, file := range files {
		if strings.HasSuffix(file, "_test.go") {
			continue
		}
		tree, err := parser.ParseFile(token.NewFileSet(), file, nil, 0)
		must(err)
		for _, decl := range tree.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !ast.IsExported(fn.Name.Name) || fn.Type.Results == nil {
				continue
			}
			index := 0
			for _, result := range fn.Type.Results.List {
				n := len(result.Names)
				if n == 0 {
					n = 1
				}
				if kind, ok := result.Type.(*ast.Ident); ok && kind.Name == "error" {
					signatures[fn.Name.Name] = index + n - 1
				}
				index += n
			}
		}
	}
	names := make([]string, 0, len(signatures))
	for name := range signatures {
		names = append(names, name)
	}
	sort.Strings(names)
	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/helper-signatures. DO NOT EDIT.\npackage plugin_sdk\n\nvar helperErrorResults = map[string]int{\n")
	for _, name := range names {
		fmt.Fprintf(&out, "%q: %d,\n", name, signatures[name])
	}
	out.WriteString("}\n")
	out.WriteString("// HelperErrorResult returns the zero-based result position that carries an error.\n// Tooling uses actual signatures, so void logging and result constructors are not mistaken for unchecked calls.\nfunc HelperErrorResult(name string) (int, bool) { index, ok := helperErrorResults[name]; return index, ok }\n")
	generated, err := format.Source(out.Bytes())
	must(err)
	const target = "helper_signatures_generated.go"
	if *check {
		actual, err := os.ReadFile(target)
		must(err)
		if !bytes.Equal(actual, generated) {
			must(fmt.Errorf("%s is stale; run go run ./scripts/helper-signatures", target))
		}
		return
	}
	must(os.WriteFile(target, generated, 0644))
}
func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
