package providerschema

// RenderGeneratedFile renders snapshot.gen.go from the vendored artifacts.
// The render is DETERMINISTIC: identical inputs produce byte-identical
// output (stable node ordering, fixed template), and the offline test
// re-renders and byte-compares against the checked-in file.

import (
	"bytes"
	"fmt"
	"strings"
)

// SchemaNode is one machine-derived schema fact from the vendored protos.
// ID is a namespaced identity; Member is the camelCase wire spelling; Kind
// is the wire value kind; Surfaces names the surfaces declaring it;
// Vocabulary carries enum value names (for enum-kind nodes) in artifact
// order.
type SchemaNode struct {
	ID         string
	Member     string
	Kind       string
	Surfaces   []string
	Vocabulary []string
}

// RenderGeneratedFile parses the vendored source and renders the complete
// snapshot.gen.go payload.
func RenderGeneratedFile() ([]byte, error) {
	nodes, err := ParseVendoredSource()
	if err != nil {
		return nil, err
	}
	m, err := LoadManifest()
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by generate.go from the vendored provider artifacts\n")
	b.WriteString("// (providerschema/source/*.proto + source/manifest.json). DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Immutable upstream inputs (see source/manifest.json for full provenance,\n")
	b.WriteString("// fetch date, and license):\n")
	for _, f := range m.Files {
		fmt.Fprintf(&b, "//   %s @ %s (%s)\n", f.Path, f.UpstreamCommitSHA, f.UpstreamCommitDate)
	}
	b.WriteString("//\n")
	b.WriteString("// Deterministic regeneration: ./generate.sh (byte-identical across runs;\n")
	b.WriteString("// TestSnapshotGeneratedExact enforces it offline).\n")
	b.WriteString("package providerschema\n\n")
	b.WriteString("// schemaNodes is the complete machine-derived node set.\n")
	b.WriteString("var schemaNodes = []SchemaNode{\n")
	for _, n := range nodes {
		surf := strings.Join(n.Surfaces, `", "`)
		fmt.Fprintf(&b, "\t{ID: %q, Member: %q, Kind: %q, Surfaces: []string{\"%s\"}},\n",
			n.ID, n.Member, n.Kind, surf)
	}
	b.WriteString("}\n")
	fmt.Fprintf(&b, "\n// schedulingArtifactOrder / mediaResolutionLevelArtifactOrder (provider enum order).\n")
	fmt.Fprintf(&b, "var schedulingArtifactOrder = []string{\"%s\"}\n", strings.Join(schedulingArtifactOrder, `", "`))
	fmt.Fprintf(&b, "var mediaResolutionLevelArtifactOrder = []string{\"%s\"}\n", strings.Join(mediaResolutionLevelArtifactOrder, `", "`))
	return b.Bytes(), nil
}
