// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/torana/v2/torana.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hook names a hook. It is NOT carried on the wire: the payload oneof is the
// sole discriminator, so a frame cannot claim one hook while carrying another's
// payload. This type exists for host and SDK code to name hooks in signatures
// and errors.
//
// An earlier draft put a hook field alongside the payload. That made
// contradictory frames — HOOK_BEFORE_REQUEST carrying a tick_request — perfectly
// valid protobuf, so "misdispatch is caught" depended on someone remembering to
// compare two fields. Deriving the hook from the payload makes the contradiction
// unrepresentable instead, which is the same lesson as dropping `handled`.
type Hook int32

const (
	Hook_HOOK_UNSPECIFIED     Hook = 0
	Hook_HOOK_BEFORE_REQUEST  Hook = 1
	Hook_HOOK_AFTER_RESPONSE  Hook = 2
	Hook_HOOK_ON_STREAM_CHUNK Hook = 3
	Hook_HOOK_ON_HTTP_REQUEST Hook = 4
	Hook_HOOK_ON_TICK         Hook = 5
)

// Enum value maps for Hook.
var (
	Hook_name = map[int32]string{
		0: "HOOK_UNSPECIFIED",
		1: "HOOK_BEFORE_REQUEST",
		2: "HOOK_AFTER_RESPONSE",
		3: "HOOK_ON_STREAM_CHUNK",
		4: "HOOK_ON_HTTP_REQUEST",
		5: "HOOK_ON_TICK",
	}
	Hook_value = map[string]int32{
		"HOOK_UNSPECIFIED":     0,
		"HOOK_BEFORE_REQUEST":  1,
		"HOOK_AFTER_RESPONSE":  2,
		"HOOK_ON_STREAM_CHUNK": 3,
		"HOOK_ON_HTTP_REQUEST": 4,
		"HOOK_ON_TICK":         5,
	}
)

func (x Hook) Enum() *Hook {
	p := new(Hook)
	*p = x
	return p
}

func (x Hook) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torana_v2_torana_proto_enumTypes[0].Descriptor()
}

func (Hook) Type() protoreflect.EnumType {
	return &file_proto_torana_v2_torana_proto_enumTypes[0]
}

func (x Hook) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook.Descriptor instead.
func (Hook) EnumDescriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{0}
}

// Disposition states what a plugin wants done with the input it was given.
//
// This replaces v1's `handled` bool, which existed only because an all-defaults
// protobuf message marshals to zero bytes, making "suppress" indistinguishable
// from "pass through". A hook that changes nothing still returns zero bytes at
// the ABI level; a hook that returns a frame must say what it means.
type Disposition int32

const (
	// Never valid in a returned frame. A frame that says nothing is a protocol
	// error, and the host traps rather than guessing.
	Disposition_DISPOSITION_UNSPECIFIED Disposition = 0
	// Use the host's input unchanged. Equivalent to returning zero bytes, and
	// accepted so a plugin can be explicit.
	Disposition_DISPOSITION_PASS Disposition = 1
	// Use the frame's payload instead of the input.
	Disposition_DISPOSITION_REPLACE Disposition = 2
	// Drop the input and emit nothing. Stream events only.
	Disposition_DISPOSITION_SUPPRESS Disposition = 3
)

// Enum value maps for Disposition.
var (
	Disposition_name = map[int32]string{
		0: "DISPOSITION_UNSPECIFIED",
		1: "DISPOSITION_PASS",
		2: "DISPOSITION_REPLACE",
		3: "DISPOSITION_SUPPRESS",
	}
	Disposition_value = map[string]int32{
		"DISPOSITION_UNSPECIFIED": 0,
		"DISPOSITION_PASS":        1,
		"DISPOSITION_REPLACE":     2,
		"DISPOSITION_SUPPRESS":    3,
	}
)

func (x Disposition) Enum() *Disposition {
	p := new(Disposition)
	*p = x
	return p
}

func (x Disposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Disposition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torana_v2_torana_proto_enumTypes[1].Descriptor()
}

func (Disposition) Type() protoreflect.EnumType {
	return &file_proto_torana_v2_torana_proto_enumTypes[1]
}

func (x Disposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Disposition.Descriptor instead.
func (Disposition) EnumDescriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{1}
}

// ErrorCode classifies a failed host call.
//
// v1 returned a bare string, and the same channel carried both the plugin's own
// stored data and the host's errors. Telling them apart took 55 lines of
// heuristics in the SDK whose own comment conceded the ambiguity was
// unresolvable. Notably, "the key is absent" and "durable state is not
// configured at all" were indistinguishable, so a plugin could not tell a fresh
// store from a disabled one.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// The capability was not granted. The plugin asked for something its manifest
	// may not even declare.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 1
	// The key, conversation or record does not exist.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 2
	// The feature exists but the operator has not configured it — no durable
	// state store, no offload provider, no pricing table.
	ErrorCode_ERROR_CODE_NOT_CONFIGURED ErrorCode = 3
	// Configured but not usable right now: upstream down, budget exhausted.
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 4
	// The plugin's arguments did not parse or did not make sense.
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 5
	// The host failed for a reason the plugin cannot act on.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_PERMISSION_DENIED",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_NOT_CONFIGURED",
		4: "ERROR_CODE_UNAVAILABLE",
		5: "ERROR_CODE_INVALID_ARGUMENT",
		6: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_PERMISSION_DENIED": 1,
		"ERROR_CODE_NOT_FOUND":         2,
		"ERROR_CODE_NOT_CONFIGURED":    3,
		"ERROR_CODE_UNAVAILABLE":       4,
		"ERROR_CODE_INVALID_ARGUMENT":  5,
		"ERROR_CODE_INTERNAL":          6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torana_v2_torana_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_torana_v2_torana_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{2}
}

// A single turn in a chat conversation.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// JSON array of multimodal parts (e.g. vision).
	ContentPartsJson  []byte      `protobuf:"bytes,3,opt,name=content_parts_json,json=contentPartsJson,proto3" json:"content_parts_json,omitempty"`
	Thinking          string      `protobuf:"bytes,4,opt,name=thinking,proto3" json:"thinking,omitempty"`
	ThinkingSignature string      `protobuf:"bytes,5,opt,name=thinking_signature,json=thinkingSignature,proto3" json:"thinking_signature,omitempty"`
	RedactedThinking  string      `protobuf:"bytes,6,opt,name=redacted_thinking,json=redactedThinking,proto3" json:"redacted_thinking,omitempty"`
	ToolCalls         []*ToolCall `protobuf:"bytes,7,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId        string      `protobuf:"bytes,8,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName          string      `protobuf:"bytes,9,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Opaque provider cache breakpoint on this message (JSON object, e.g.
	// Anthropic {"type":"ephemeral"}). Preserved verbatim across the plugin
	// boundary so mutating plugins don't strip prompt-cache markers.
	CacheControlJson []byte `protobuf:"bytes,10,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentPartsJson() []byte {
	if x != nil {
		return x.ContentPartsJson
	}
	return nil
}

func (x *Message) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *Message) GetThinkingSignature() string {
	if x != nil {
		return x.ThinkingSignature
	}
	return ""
}

func (x *Message) GetRedactedThinking() string {
	if x != nil {
		return x.RedactedThinking
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Message) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// An assistant's request to invoke a tool.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Verbatim JSON. Never decode and re-encode: key order is part of the
	// cacheable prefix.
	ArgumentsJson []byte `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Opaque provider token bound to this call (e.g. Gemini thoughtSignature).
	// Preserved across round-trips so replayed history keeps the model's
	// reasoning binding; empty for providers that don't emit one.
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *ToolCall) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// Describes a function available to the model.
type ToolDef struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Verbatim JSON Schema. Same rule as arguments_json.
	ParametersJson []byte `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Strict         bool   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	// Opaque cache breakpoint after this tool definition (JSON object).
	CacheControlJson []byte `protobuf:"bytes,5,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDef) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *ToolDef) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *ToolDef) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// Token accounting reported by the provider.
type Usage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InputTokens  int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// Input tokens served from the provider's prompt cache.
	CacheReadTokens int32 `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	// Input tokens written to the cache this turn; 0 if unreported.
	CacheWriteTokens int32 `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCacheReadTokens() int32 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Usage) GetCacheWriteTokens() int32 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

// Canonical representation of a chat completion request.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,7,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	StopSequences []string               `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Unparsed provider fields, passed through transparently as JSON.
	ProviderExtensionsJson []byte `protobuf:"bytes,9,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	SafetySettingsJson     []byte `protobuf:"bytes,10,opt,name=safety_settings_json,json=safetySettingsJson,proto3" json:"safety_settings_json,omitempty"`
	// Proxy-internal metadata the host publishes to plugins: the routed provider,
	// the conversation id, the request path. Never serialized to the wire.
	//
	// In v1 this doubled as the channel plugins used to return verdicts, which is
	// why a plugin could block a request without holding the capability to block
	// — the host read the key long after it had lost track of who wrote it.
	// Verdicts are host calls in v2, so this is host-owned: a plugin changing it
	// is a protocol violation, not a grantable edit.
	ToranaMetaJson []byte `protobuf:"bytes,11,opt,name=torana_meta_json,json=toranaMetaJson,proto3" json:"torana_meta_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *ChatRequest) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

func (x *ChatRequest) GetSafetySettingsJson() []byte {
	if x != nil {
		return x.SafetySettingsJson
	}
	return nil
}

func (x *ChatRequest) GetToranaMetaJson() []byte {
	if x != nil {
		return x.ToranaMetaJson
	}
	return nil
}

// Canonical representation of a completed, non-streamed response.
//
// v1 had no such message. The response hook received a ChatRequest carrying,
// depending on which of three code paths produced it, a synthesized assistant
// message, the outbound request history, or nothing at all — a difference the
// plugin could not observe. Four independent auditors reported that as a bug.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model that actually answered, which may differ from the one requested.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Provider's response id, empty when it reported none.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The assistant's turn.
	Message      *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason string   `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage        *Usage   `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	// Upstream HTTP status. Non-2xx responses reach observational hooks too.
	UpstreamStatus int32 `protobuf:"varint,6,opt,name=upstream_status,json=upstreamStatus,proto3" json:"upstream_status,omitempty"`
	DurationMs     int64 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Provider fields Torana did not model, verbatim.
	ProviderExtensionsJson []byte `protobuf:"bytes,8,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{5}
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatResponse) GetUpstreamStatus() int32 {
	if x != nil {
		return x.UpstreamStatus
	}
	return 0
}

func (x *ChatResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ChatResponse) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

type ToolCallStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque provider token on the call (Gemini thoughtSignature); empty otherwise.
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStart) Reset() {
	*x = ToolCallStart{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStart) ProtoMessage() {}

func (x *ToolCallStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStart.ProtoReflect.Descriptor instead.
func (*ToolCallStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCallStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallStart) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ToolCallDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ArgumentsDelta string                 `protobuf:"bytes,2,opt,name=arguments_delta,json=argumentsDelta,proto3" json:"arguments_delta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetArgumentsDelta() string {
	if x != nil {
		return x.ArgumentsDelta
	}
	return ""
}

type ToolCallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEnd) Reset() {
	*x = ToolCallEnd{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEnd) ProtoMessage() {}

func (x *ToolCallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEnd.ProtoReflect.Descriptor instead.
func (*ToolCallEnd) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCallEnd) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{9}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Structural boundaries in a streamed response.
//
// v1 emitted deltas and tool-call boundaries and nothing else, so a plugin that
// needed to know where a message or a content block began had to infer it from
// the delta sequence. Both stream plugins in the official set reimplemented that
// inference, ~60 lines each, and it is the single most copy-pasted thing a
// stream plugin does.
type MessageStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "assistant" for every provider Torana currently speaks, but carried rather
	// than assumed.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStart) Reset() {
	*x = MessageStart{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStart) ProtoMessage() {}

func (x *MessageStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStart.ProtoReflect.Descriptor instead.
func (*MessageStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{10}
}

func (x *MessageStart) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageStart) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type MessageStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinishReason  string                 `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStop) Reset() {
	*x = MessageStop{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStop) ProtoMessage() {}

func (x *MessageStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStop.ProtoReflect.Descriptor instead.
func (*MessageStop) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{11}
}

func (x *MessageStop) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// ContentBlockStart opens a text, thinking or tool-call block. Deltas that
// follow belong to it until the matching stop.
type ContentBlockStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// "text", "thinking", "tool_call", or a provider-specific name passed
	// through verbatim.
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStart) Reset() {
	*x = ContentBlockStart{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStart) ProtoMessage() {}

func (x *ContentBlockStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStart.ProtoReflect.Descriptor instead.
func (*ContentBlockStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{12}
}

func (x *ContentBlockStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ContentBlockStart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ContentBlockStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStop) Reset() {
	*x = ContentBlockStop{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStop) ProtoMessage() {}

func (x *ContentBlockStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStop.ProtoReflect.Descriptor instead.
func (*ContentBlockStop) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{13}
}

func (x *ContentBlockStop) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_TextDelta
	//	*StreamEvent_ThinkingDelta
	//	*StreamEvent_ToolCallStart
	//	*StreamEvent_ToolCallDelta
	//	*StreamEvent_ToolCallEnd
	//	*StreamEvent_FinishReason
	//	*StreamEvent_Usage
	//	*StreamEvent_Error
	//	*StreamEvent_SignatureDelta
	//	*StreamEvent_MessageStart
	//	*StreamEvent_MessageStop
	//	*StreamEvent_ContentBlockStart
	//	*StreamEvent_ContentBlockStop
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{14}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetTextDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetThinkingDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetToolCallStart() *ToolCallStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallStart); ok {
			return x.ToolCallStart
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallEnd() *ToolCallEnd {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallEnd); ok {
			return x.ToolCallEnd
		}
	}
	return nil
}

func (x *StreamEvent) GetFinishReason() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_FinishReason); ok {
			return x.FinishReason
		}
	}
	return ""
}

func (x *StreamEvent) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *StreamEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamEvent) GetSignatureDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_SignatureDelta); ok {
			return x.SignatureDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetMessageStart() *MessageStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStart); ok {
			return x.MessageStart
		}
	}
	return nil
}

func (x *StreamEvent) GetMessageStop() *MessageStop {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStop); ok {
			return x.MessageStop
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStart() *ContentBlockStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStart); ok {
			return x.ContentBlockStart
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStop() *ContentBlockStop {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStop); ok {
			return x.ContentBlockStop
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_TextDelta struct {
	TextDelta string `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type StreamEvent_ThinkingDelta struct {
	ThinkingDelta string `protobuf:"bytes,2,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type StreamEvent_ToolCallStart struct {
	ToolCallStart *ToolCallStart `protobuf:"bytes,3,opt,name=tool_call_start,json=toolCallStart,proto3,oneof"`
}

type StreamEvent_ToolCallDelta struct {
	ToolCallDelta *ToolCallDelta `protobuf:"bytes,4,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type StreamEvent_ToolCallEnd struct {
	ToolCallEnd *ToolCallEnd `protobuf:"bytes,5,opt,name=tool_call_end,json=toolCallEnd,proto3,oneof"`
}

type StreamEvent_FinishReason struct {
	FinishReason string `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3,oneof"`
}

type StreamEvent_Usage struct {
	Usage *Usage `protobuf:"bytes,7,opt,name=usage,proto3,oneof"`
}

type StreamEvent_Error struct {
	Error *StreamError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type StreamEvent_SignatureDelta struct {
	// Opaque provider signature paired with the surrounding block (Gemini
	// thoughtSignature on a standalone text/thought part).
	SignatureDelta string `protobuf:"bytes,9,opt,name=signature_delta,json=signatureDelta,proto3,oneof"`
}

type StreamEvent_MessageStart struct {
	MessageStart *MessageStart `protobuf:"bytes,10,opt,name=message_start,json=messageStart,proto3,oneof"`
}

type StreamEvent_MessageStop struct {
	MessageStop *MessageStop `protobuf:"bytes,11,opt,name=message_stop,json=messageStop,proto3,oneof"`
}

type StreamEvent_ContentBlockStart struct {
	ContentBlockStart *ContentBlockStart `protobuf:"bytes,12,opt,name=content_block_start,json=contentBlockStart,proto3,oneof"`
}

type StreamEvent_ContentBlockStop struct {
	ContentBlockStop *ContentBlockStop `protobuf:"bytes,13,opt,name=content_block_stop,json=contentBlockStop,proto3,oneof"`
}

func (*StreamEvent_TextDelta) isStreamEvent_Event() {}

func (*StreamEvent_ThinkingDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallStart) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallEnd) isStreamEvent_Event() {}

func (*StreamEvent_FinishReason) isStreamEvent_Event() {}

func (*StreamEvent_Usage) isStreamEvent_Event() {}

func (*StreamEvent_Error) isStreamEvent_Event() {}

func (*StreamEvent_SignatureDelta) isStreamEvent_Event() {}

func (*StreamEvent_MessageStart) isStreamEvent_Event() {}

func (*StreamEvent_MessageStop) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStart) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStop) isStreamEvent_Event() {}

// StreamEvents exists because a protobuf oneof cannot hold a repeated field.
type StreamEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StreamEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvents) Reset() {
	*x = StreamEvents{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvents) ProtoMessage() {}

func (x *StreamEvents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvents.ProtoReflect.Descriptor instead.
func (*StreamEvents) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{15}
}

func (x *StreamEvents) GetEvents() []*StreamEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Incoming HTTP request forwarded to a plugin's run_on_http_request hook.
// Built directly from net/http — does not cross the chat IR.
type HttpRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Raw query string, without the leading "?". v1 dropped this entirely, so a
	// plugin serving a page could not read its own query parameters.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// "http" or "https".
	Scheme string `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Caller address, for a plugin that wants to refuse non-local requests
	// itself. The host has already applied its own guard before dispatching.
	RemoteAddr string `protobuf:"bytes,5,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// JSON-encoded map of request headers (map[string][]string), filtered by the
	// host to the same allowlist the chat path uses.
	HeadersJson   []byte `protobuf:"bytes,6,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{16}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HttpRequest) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Response produced by a plugin's run_on_http_request hook.
type HttpResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// JSON-encoded map of response headers (map[string][]string). The host
	// applies its own allowlist; anything outside it fails the response.
	HeadersJson   []byte `protobuf:"bytes,2,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{17}
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Fired periodically by the host, with no request in flight.
//
// Every other hook is reactive: a plugin can only act while a request is
// passing through it. This one exists so a plugin can act when nothing is
// happening — refreshing a provider cache before it lapses, emitting a periodic
// report, expiring its own state.
//
// Requires env.background_tick. Running code with no request in flight is a
// capability an operator should grant deliberately: a plugin holding it can act
// — and spend — outside any request the operator can see.
type TickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing within one scheduler, starting at 1. Resets if the
	// scheduler restarts, so treat it as an ordering hint rather than a durable
	// counter.
	TickId uint64 `protobuf:"varint,1,opt,name=tick_id,json=tickId,proto3" json:"tick_id,omitempty"`
	// Host wall-clock time. Plugins have no clock of their own: WASI preview1
	// exposes none, and this is the only time source they get.
	UnixMillis int64 `protobuf:"varint,2,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	// Configured interval, so a plugin can reason about elapsed time without
	// assuming a particular cadence.
	IntervalMs    int64 `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{18}
}

func (x *TickRequest) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

func (x *TickRequest) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *TickRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// What a plugin did during a tick. Reported for observability only; the host
// attaches no meaning to it.
type TickOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       int32                  `protobuf:"varint,1,opt,name=actions,proto3" json:"actions,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickOutcome) Reset() {
	*x = TickOutcome{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickOutcome) ProtoMessage() {}

func (x *TickOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickOutcome.ProtoReflect.Descriptor instead.
func (*TickOutcome) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{19}
}

func (x *TickOutcome) GetActions() int32 {
	if x != nil {
		return x.Actions
	}
	return 0
}

func (x *TickOutcome) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// HookInput is what every hook receives. The payload determines which hook this
// is; there is no separate hook field to contradict it.
type HookInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minor version of the v2 contract the host is speaking. Additive changes
	// bump this; a plugin may use it to detect fields it can rely on.
	AbiMinor uint32 `protobuf:"varint,1,opt,name=abi_minor,json=abiMinor,proto3" json:"abi_minor,omitempty"`
	// Host-assigned request id, stable for the life of one request. Stream hooks
	// for the same response share it.
	RequestId uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Whether the host will apply a REPLACE to this dispatch.
	//
	// False only for run_after_response when the response was streamed or was an
	// upstream error: the bytes have already gone to the caller, or there is no
	// body to rewrite, so a returned replacement is discarded. run_before_request
	// and run_on_stream_chunk are always mutable — a stream plugin can and does
	// replace, suppress and fan out events.
	//
	// v1 offered no such signal, so a plugin learned its mutations were being
	// discarded only by their having no effect.
	Mutable bool `protobuf:"varint,3,opt,name=mutable,proto3" json:"mutable,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HookInput_ChatRequest
	//	*HookInput_ChatResponse
	//	*HookInput_StreamEvent
	//	*HookInput_HttpRequest
	//	*HookInput_TickRequest
	Payload       isHookInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookInput) Reset() {
	*x = HookInput{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookInput) ProtoMessage() {}

func (x *HookInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookInput.ProtoReflect.Descriptor instead.
func (*HookInput) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{20}
}

func (x *HookInput) GetAbiMinor() uint32 {
	if x != nil {
		return x.AbiMinor
	}
	return 0
}

func (x *HookInput) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HookInput) GetMutable() bool {
	if x != nil {
		return x.Mutable
	}
	return false
}

func (x *HookInput) GetPayload() isHookInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookInput) GetChatRequest() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_ChatRequest); ok {
			return x.ChatRequest
		}
	}
	return nil
}

func (x *HookInput) GetChatResponse() *ChatResponse {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_ChatResponse); ok {
			return x.ChatResponse
		}
	}
	return nil
}

func (x *HookInput) GetStreamEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_StreamEvent); ok {
			return x.StreamEvent
		}
	}
	return nil
}

func (x *HookInput) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *HookInput) GetTickRequest() *TickRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_TickRequest); ok {
			return x.TickRequest
		}
	}
	return nil
}

type isHookInput_Payload interface {
	isHookInput_Payload()
}

type HookInput_ChatRequest struct {
	ChatRequest *ChatRequest `protobuf:"bytes,4,opt,name=chat_request,json=chatRequest,proto3,oneof"`
}

type HookInput_ChatResponse struct {
	ChatResponse *ChatResponse `protobuf:"bytes,5,opt,name=chat_response,json=chatResponse,proto3,oneof"`
}

type HookInput_StreamEvent struct {
	StreamEvent *StreamEvent `protobuf:"bytes,6,opt,name=stream_event,json=streamEvent,proto3,oneof"`
}

type HookInput_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,7,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type HookInput_TickRequest struct {
	TickRequest *TickRequest `protobuf:"bytes,8,opt,name=tick_request,json=tickRequest,proto3,oneof"`
}

func (*HookInput_ChatRequest) isHookInput_Payload() {}

func (*HookInput_ChatResponse) isHookInput_Payload() {}

func (*HookInput_StreamEvent) isHookInput_Payload() {}

func (*HookInput_HttpRequest) isHookInput_Payload() {}

func (*HookInput_TickRequest) isHookInput_Payload() {}

// HookResult is what every hook returns, when it returns anything at all.
//
// Returning zero bytes still means "pass through" — that is unambiguous at the
// ABI level, because it is a length rather than a message.
type HookResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Disposition Disposition            `protobuf:"varint,1,opt,name=disposition,proto3,enum=torana.v2.Disposition" json:"disposition,omitempty"`
	// The payload's type must match the hook that was dispatched. A result
	// carrying another hook's payload is a protocol error.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*HookResult_ChatRequest
	//	*HookResult_ChatResponse
	//	*HookResult_StreamEvents
	//	*HookResult_HttpResponse
	//	*HookResult_TickOutcome
	Payload       isHookResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{21}
}

func (x *HookResult) GetDisposition() Disposition {
	if x != nil {
		return x.Disposition
	}
	return Disposition_DISPOSITION_UNSPECIFIED
}

func (x *HookResult) GetPayload() isHookResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookResult) GetChatRequest() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookResult_ChatRequest); ok {
			return x.ChatRequest
		}
	}
	return nil
}

func (x *HookResult) GetChatResponse() *ChatResponse {
	if x != nil {
		if x, ok := x.Payload.(*HookResult_ChatResponse); ok {
			return x.ChatResponse
		}
	}
	return nil
}

func (x *HookResult) GetStreamEvents() *StreamEvents {
	if x != nil {
		if x, ok := x.Payload.(*HookResult_StreamEvents); ok {
			return x.StreamEvents
		}
	}
	return nil
}

func (x *HookResult) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*HookResult_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *HookResult) GetTickOutcome() *TickOutcome {
	if x != nil {
		if x, ok := x.Payload.(*HookResult_TickOutcome); ok {
			return x.TickOutcome
		}
	}
	return nil
}

type isHookResult_Payload interface {
	isHookResult_Payload()
}

type HookResult_ChatRequest struct {
	ChatRequest *ChatRequest `protobuf:"bytes,2,opt,name=chat_request,json=chatRequest,proto3,oneof"`
}

type HookResult_ChatResponse struct {
	ChatResponse *ChatResponse `protobuf:"bytes,3,opt,name=chat_response,json=chatResponse,proto3,oneof"`
}

type HookResult_StreamEvents struct {
	StreamEvents *StreamEvents `protobuf:"bytes,4,opt,name=stream_events,json=streamEvents,proto3,oneof"`
}

type HookResult_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,5,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type HookResult_TickOutcome struct {
	TickOutcome *TickOutcome `protobuf:"bytes,6,opt,name=tick_outcome,json=tickOutcome,proto3,oneof"`
}

func (*HookResult_ChatRequest) isHookResult_Payload() {}

func (*HookResult_ChatResponse) isHookResult_Payload() {}

func (*HookResult_StreamEvents) isHookResult_Payload() {}

func (*HookResult_HttpResponse) isHookResult_Payload() {}

func (*HookResult_TickOutcome) isHookResult_Payload() {}

type HostError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=torana.v2.ErrorCode" json:"code,omitempty"`
	// Human-readable, for logs. Plugins should branch on `code`, never on this.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostError) Reset() {
	*x = HostError{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostError) ProtoMessage() {}

func (x *HostError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostError.ProtoReflect.Descriptor instead.
func (*HostError) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{22}
}

func (x *HostError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *HostError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HostCallResult is what every host call returns.
//
// A successful call with no value sets `value` to empty bytes, which is
// distinguishable from an error — unlike v1, where an empty string meant
// "granted but no value", "cache miss", "key absent", "feature unconfigured",
// and "the host refused to write an empty payload", all at once.
type HostCallResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*HostCallResult_Value
	//	*HostCallResult_Error
	Result        isHostCallResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCallResult) Reset() {
	*x = HostCallResult{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallResult) ProtoMessage() {}

func (x *HostCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallResult.ProtoReflect.Descriptor instead.
func (*HostCallResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{23}
}

func (x *HostCallResult) GetResult() isHostCallResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HostCallResult) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*HostCallResult_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *HostCallResult) GetError() *HostError {
	if x != nil {
		if x, ok := x.Result.(*HostCallResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isHostCallResult_Result interface {
	isHostCallResult_Result()
}

type HostCallResult_Value struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type HostCallResult_Error struct {
	Error *HostError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*HostCallResult_Value) isHostCallResult_Result() {}

func (*HostCallResult_Error) isHostCallResult_Result() {}

var File_proto_torana_v2_torana_proto protoreflect.FileDescriptor

const file_proto_torana_v2_torana_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/torana/v2/torana.proto\x12\ttorana.v2\"\xfe\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x12content_parts_json\x18\x03 \x01(\fR\x10contentPartsJson\x12\x1a\n" +
	"\bthinking\x18\x04 \x01(\tR\bthinking\x12-\n" +
	"\x12thinking_signature\x18\x05 \x01(\tR\x11thinkingSignature\x12+\n" +
	"\x11redacted_thinking\x18\x06 \x01(\tR\x10redactedThinking\x122\n" +
	"\n" +
	"tool_calls\x18\a \x03(\v2\x13.torana.v2.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\b \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\t \x01(\tR\btoolName\x12,\n" +
	"\x12cache_control_json\x18\n" +
	" \x01(\fR\x10cacheControlJson\"s\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xae\x01\n" +
	"\aToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\fR\x0eparametersJson\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\x12,\n" +
	"\x12cache_control_json\x18\x05 \x01(\fR\x10cacheControlJson\"\xa9\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x05R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x05R\x10cacheWriteTokens\"\xe0\x03\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.torana.v2.MessageR\bmessages\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.torana.v2.ToolDefR\x05tools\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\"\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x01H\x01R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\a \x01(\x01H\x02R\x04topP\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x128\n" +
	"\x18provider_extensions_json\x18\t \x01(\fR\x16providerExtensionsJson\x120\n" +
	"\x14safety_settings_json\x18\n" +
	" \x01(\fR\x12safetySettingsJson\x12(\n" +
	"\x10torana_meta_json\x18\v \x01(\fR\x0etoranaMetaJsonB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_p\"\xb3\x02\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\amessage\x18\x03 \x01(\v2\x12.torana.v2.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12&\n" +
	"\x05usage\x18\x05 \x01(\v2\x10.torana.v2.UsageR\x05usage\x12'\n" +
	"\x0fupstream_status\x18\x06 \x01(\x05R\x0eupstreamStatus\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x128\n" +
	"\x18provider_extensions_json\x18\b \x01(\fR\x16providerExtensionsJson\"g\n" +
	"\rToolCallStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"N\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12'\n" +
	"\x0farguments_delta\x18\x02 \x01(\tR\x0eargumentsDelta\"#\n" +
	"\vToolCallEnd\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\";\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\fMessageStart\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"2\n" +
	"\vMessageStop\x12#\n" +
	"\rfinish_reason\x18\x01 \x01(\tR\ffinishReason\"=\n" +
	"\x11ContentBlockStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"(\n" +
	"\x10ContentBlockStop\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"\xec\x05\n" +
	"\vStreamEvent\x12\x1f\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tH\x00R\ttextDelta\x12'\n" +
	"\x0ethinking_delta\x18\x02 \x01(\tH\x00R\rthinkingDelta\x12B\n" +
	"\x0ftool_call_start\x18\x03 \x01(\v2\x18.torana.v2.ToolCallStartH\x00R\rtoolCallStart\x12B\n" +
	"\x0ftool_call_delta\x18\x04 \x01(\v2\x18.torana.v2.ToolCallDeltaH\x00R\rtoolCallDelta\x12<\n" +
	"\rtool_call_end\x18\x05 \x01(\v2\x16.torana.v2.ToolCallEndH\x00R\vtoolCallEnd\x12%\n" +
	"\rfinish_reason\x18\x06 \x01(\tH\x00R\ffinishReason\x12(\n" +
	"\x05usage\x18\a \x01(\v2\x10.torana.v2.UsageH\x00R\x05usage\x12.\n" +
	"\x05error\x18\b \x01(\v2\x16.torana.v2.StreamErrorH\x00R\x05error\x12)\n" +
	"\x0fsignature_delta\x18\t \x01(\tH\x00R\x0esignatureDelta\x12>\n" +
	"\rmessage_start\x18\n" +
	" \x01(\v2\x17.torana.v2.MessageStartH\x00R\fmessageStart\x12;\n" +
	"\fmessage_stop\x18\v \x01(\v2\x16.torana.v2.MessageStopH\x00R\vmessageStop\x12N\n" +
	"\x13content_block_start\x18\f \x01(\v2\x1c.torana.v2.ContentBlockStartH\x00R\x11contentBlockStart\x12K\n" +
	"\x12content_block_stop\x18\r \x01(\v2\x1b.torana.v2.ContentBlockStopH\x00R\x10contentBlockStopB\a\n" +
	"\x05event\">\n" +
	"\fStreamEvents\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.torana.v2.StreamEventR\x06events\"\xbf\x01\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x1f\n" +
	"\vremote_addr\x18\x05 \x01(\tR\n" +
	"remoteAddr\x12!\n" +
	"\fheaders_json\x18\x06 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\"]\n" +
	"\fHttpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12!\n" +
	"\fheaders_json\x18\x02 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"h\n" +
	"\vTickRequest\x12\x17\n" +
	"\atick_id\x18\x01 \x01(\x04R\x06tickId\x12\x1f\n" +
	"\vunix_millis\x18\x02 \x01(\x03R\n" +
	"unixMillis\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x03R\n" +
	"intervalMs\";\n" +
	"\vTickOutcome\x12\x18\n" +
	"\aactions\x18\x01 \x01(\x05R\aactions\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"\xa0\x03\n" +
	"\tHookInput\x12\x1b\n" +
	"\tabi_minor\x18\x01 \x01(\rR\babiMinor\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x18\n" +
	"\amutable\x18\x03 \x01(\bR\amutable\x12;\n" +
	"\fchat_request\x18\x04 \x01(\v2\x16.torana.v2.ChatRequestH\x00R\vchatRequest\x12>\n" +
	"\rchat_response\x18\x05 \x01(\v2\x17.torana.v2.ChatResponseH\x00R\fchatResponse\x12;\n" +
	"\fstream_event\x18\x06 \x01(\v2\x16.torana.v2.StreamEventH\x00R\vstreamEvent\x12;\n" +
	"\fhttp_request\x18\a \x01(\v2\x16.torana.v2.HttpRequestH\x00R\vhttpRequest\x12;\n" +
	"\ftick_request\x18\b \x01(\v2\x16.torana.v2.TickRequestH\x00R\vtickRequestB\t\n" +
	"\apayload\"\x8b\x03\n" +
	"\n" +
	"HookResult\x128\n" +
	"\vdisposition\x18\x01 \x01(\x0e2\x16.torana.v2.DispositionR\vdisposition\x12;\n" +
	"\fchat_request\x18\x02 \x01(\v2\x16.torana.v2.ChatRequestH\x00R\vchatRequest\x12>\n" +
	"\rchat_response\x18\x03 \x01(\v2\x17.torana.v2.ChatResponseH\x00R\fchatResponse\x12>\n" +
	"\rstream_events\x18\x04 \x01(\v2\x17.torana.v2.StreamEventsH\x00R\fstreamEvents\x12>\n" +
	"\rhttp_response\x18\x05 \x01(\v2\x17.torana.v2.HttpResponseH\x00R\fhttpResponse\x12;\n" +
	"\ftick_outcome\x18\x06 \x01(\v2\x16.torana.v2.TickOutcomeH\x00R\vtickOutcomeB\t\n" +
	"\apayload\"O\n" +
	"\tHostError\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.torana.v2.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x0eHostCallResult\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x14.torana.v2.HostErrorH\x00R\x05errorB\b\n" +
	"\x06result*\x94\x01\n" +
	"\x04Hook\x12\x14\n" +
	"\x10HOOK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HOOK_BEFORE_REQUEST\x10\x01\x12\x17\n" +
	"\x13HOOK_AFTER_RESPONSE\x10\x02\x12\x18\n" +
	"\x14HOOK_ON_STREAM_CHUNK\x10\x03\x12\x18\n" +
	"\x14HOOK_ON_HTTP_REQUEST\x10\x04\x12\x10\n" +
	"\fHOOK_ON_TICK\x10\x05*s\n" +
	"\vDisposition\x12\x1b\n" +
	"\x17DISPOSITION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DISPOSITION_PASS\x10\x01\x12\x17\n" +
	"\x13DISPOSITION_REPLACE\x10\x02\x12\x18\n" +
	"\x14DISPOSITION_SUPPRESS\x10\x03*\xd8\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_NOT_CONFIGURED\x10\x03\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x06B0Z.github.com/torana-edge/torana-plugin-sdk/pb/v2b\x06proto3"

var (
	file_proto_torana_v2_torana_proto_rawDescOnce sync.Once
	file_proto_torana_v2_torana_proto_rawDescData []byte
)

func file_proto_torana_v2_torana_proto_rawDescGZIP() []byte {
	file_proto_torana_v2_torana_proto_rawDescOnce.Do(func() {
		file_proto_torana_v2_torana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torana_v2_torana_proto_rawDesc), len(file_proto_torana_v2_torana_proto_rawDesc)))
	})
	return file_proto_torana_v2_torana_proto_rawDescData
}

var file_proto_torana_v2_torana_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_torana_v2_torana_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_torana_v2_torana_proto_goTypes = []any{
	(Hook)(0),                 // 0: torana.v2.Hook
	(Disposition)(0),          // 1: torana.v2.Disposition
	(ErrorCode)(0),            // 2: torana.v2.ErrorCode
	(*Message)(nil),           // 3: torana.v2.Message
	(*ToolCall)(nil),          // 4: torana.v2.ToolCall
	(*ToolDef)(nil),           // 5: torana.v2.ToolDef
	(*Usage)(nil),             // 6: torana.v2.Usage
	(*ChatRequest)(nil),       // 7: torana.v2.ChatRequest
	(*ChatResponse)(nil),      // 8: torana.v2.ChatResponse
	(*ToolCallStart)(nil),     // 9: torana.v2.ToolCallStart
	(*ToolCallDelta)(nil),     // 10: torana.v2.ToolCallDelta
	(*ToolCallEnd)(nil),       // 11: torana.v2.ToolCallEnd
	(*StreamError)(nil),       // 12: torana.v2.StreamError
	(*MessageStart)(nil),      // 13: torana.v2.MessageStart
	(*MessageStop)(nil),       // 14: torana.v2.MessageStop
	(*ContentBlockStart)(nil), // 15: torana.v2.ContentBlockStart
	(*ContentBlockStop)(nil),  // 16: torana.v2.ContentBlockStop
	(*StreamEvent)(nil),       // 17: torana.v2.StreamEvent
	(*StreamEvents)(nil),      // 18: torana.v2.StreamEvents
	(*HttpRequest)(nil),       // 19: torana.v2.HttpRequest
	(*HttpResponse)(nil),      // 20: torana.v2.HttpResponse
	(*TickRequest)(nil),       // 21: torana.v2.TickRequest
	(*TickOutcome)(nil),       // 22: torana.v2.TickOutcome
	(*HookInput)(nil),         // 23: torana.v2.HookInput
	(*HookResult)(nil),        // 24: torana.v2.HookResult
	(*HostError)(nil),         // 25: torana.v2.HostError
	(*HostCallResult)(nil),    // 26: torana.v2.HostCallResult
}
var file_proto_torana_v2_torana_proto_depIdxs = []int32{
	4,  // 0: torana.v2.Message.tool_calls:type_name -> torana.v2.ToolCall
	3,  // 1: torana.v2.ChatRequest.messages:type_name -> torana.v2.Message
	5,  // 2: torana.v2.ChatRequest.tools:type_name -> torana.v2.ToolDef
	3,  // 3: torana.v2.ChatResponse.message:type_name -> torana.v2.Message
	6,  // 4: torana.v2.ChatResponse.usage:type_name -> torana.v2.Usage
	9,  // 5: torana.v2.StreamEvent.tool_call_start:type_name -> torana.v2.ToolCallStart
	10, // 6: torana.v2.StreamEvent.tool_call_delta:type_name -> torana.v2.ToolCallDelta
	11, // 7: torana.v2.StreamEvent.tool_call_end:type_name -> torana.v2.ToolCallEnd
	6,  // 8: torana.v2.StreamEvent.usage:type_name -> torana.v2.Usage
	12, // 9: torana.v2.StreamEvent.error:type_name -> torana.v2.StreamError
	13, // 10: torana.v2.StreamEvent.message_start:type_name -> torana.v2.MessageStart
	14, // 11: torana.v2.StreamEvent.message_stop:type_name -> torana.v2.MessageStop
	15, // 12: torana.v2.StreamEvent.content_block_start:type_name -> torana.v2.ContentBlockStart
	16, // 13: torana.v2.StreamEvent.content_block_stop:type_name -> torana.v2.ContentBlockStop
	17, // 14: torana.v2.StreamEvents.events:type_name -> torana.v2.StreamEvent
	7,  // 15: torana.v2.HookInput.chat_request:type_name -> torana.v2.ChatRequest
	8,  // 16: torana.v2.HookInput.chat_response:type_name -> torana.v2.ChatResponse
	17, // 17: torana.v2.HookInput.stream_event:type_name -> torana.v2.StreamEvent
	19, // 18: torana.v2.HookInput.http_request:type_name -> torana.v2.HttpRequest
	21, // 19: torana.v2.HookInput.tick_request:type_name -> torana.v2.TickRequest
	1,  // 20: torana.v2.HookResult.disposition:type_name -> torana.v2.Disposition
	7,  // 21: torana.v2.HookResult.chat_request:type_name -> torana.v2.ChatRequest
	8,  // 22: torana.v2.HookResult.chat_response:type_name -> torana.v2.ChatResponse
	18, // 23: torana.v2.HookResult.stream_events:type_name -> torana.v2.StreamEvents
	20, // 24: torana.v2.HookResult.http_response:type_name -> torana.v2.HttpResponse
	22, // 25: torana.v2.HookResult.tick_outcome:type_name -> torana.v2.TickOutcome
	2,  // 26: torana.v2.HostError.code:type_name -> torana.v2.ErrorCode
	25, // 27: torana.v2.HostCallResult.error:type_name -> torana.v2.HostError
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_torana_v2_torana_proto_init() }
func file_proto_torana_v2_torana_proto_init() {
	if File_proto_torana_v2_torana_proto != nil {
		return
	}
	file_proto_torana_v2_torana_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_torana_v2_torana_proto_msgTypes[14].OneofWrappers = []any{
		(*StreamEvent_TextDelta)(nil),
		(*StreamEvent_ThinkingDelta)(nil),
		(*StreamEvent_ToolCallStart)(nil),
		(*StreamEvent_ToolCallDelta)(nil),
		(*StreamEvent_ToolCallEnd)(nil),
		(*StreamEvent_FinishReason)(nil),
		(*StreamEvent_Usage)(nil),
		(*StreamEvent_Error)(nil),
		(*StreamEvent_SignatureDelta)(nil),
		(*StreamEvent_MessageStart)(nil),
		(*StreamEvent_MessageStop)(nil),
		(*StreamEvent_ContentBlockStart)(nil),
		(*StreamEvent_ContentBlockStop)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[20].OneofWrappers = []any{
		(*HookInput_ChatRequest)(nil),
		(*HookInput_ChatResponse)(nil),
		(*HookInput_StreamEvent)(nil),
		(*HookInput_HttpRequest)(nil),
		(*HookInput_TickRequest)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[21].OneofWrappers = []any{
		(*HookResult_ChatRequest)(nil),
		(*HookResult_ChatResponse)(nil),
		(*HookResult_StreamEvents)(nil),
		(*HookResult_HttpResponse)(nil),
		(*HookResult_TickOutcome)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[23].OneofWrappers = []any{
		(*HostCallResult_Value)(nil),
		(*HostCallResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torana_v2_torana_proto_rawDesc), len(file_proto_torana_v2_torana_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_torana_v2_torana_proto_goTypes,
		DependencyIndexes: file_proto_torana_v2_torana_proto_depIdxs,
		EnumInfos:         file_proto_torana_v2_torana_proto_enumTypes,
		MessageInfos:      file_proto_torana_v2_torana_proto_msgTypes,
	}.Build()
	File_proto_torana_v2_torana_proto = out.File
	file_proto_torana_v2_torana_proto_goTypes = nil
	file_proto_torana_v2_torana_proto_depIdxs = nil
}
