// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/torana/v2/torana.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hook names a hook. It is NOT carried on the wire: the payload oneof is the
// sole discriminator, so a frame cannot claim one hook while carrying another's
// payload. This type exists for host and SDK code to name hooks in signatures
// and errors.
//
// An earlier draft put a hook field alongside the payload. That made
// contradictory frames — HOOK_BEFORE_REQUEST carrying a tick_request — perfectly
// valid protobuf, so "misdispatch is caught" depended on someone remembering to
// compare two fields. Deriving the hook from the payload makes the contradiction
// unrepresentable instead, which is the same lesson as dropping `handled`.
//
// The WASM boundary completes that story: guests export one run_hook, so there
// is no second discriminator at the export name either. request_id is not a
// WASM argument — it is only on HookInput — so the host cannot disagree with
// the envelope about which request a call belongs to.
//
// Guests also export supported_hooks() -> u32. Bit N is set when Hook value N
// is implemented:
//
//	bit 1 = HOOK_BEFORE_REQUEST
//	bit 2 = HOOK_AFTER_RESPONSE
//	bit 3 = HOOK_ON_STREAM_CHUNK
//	bit 4 = HOOK_ON_HTTP_REQUEST
//	bit 5 = HOOK_ON_TICK
//
// The bitmap must exactly equal the manifest's hook set. Bit 0 and every
// unassigned bit are invalid. A missing bit (declared, not registered) or an
// unexpected bit (registered, not declared) is a load-time error. Hook values
// that participate in this export are limited to 1..31 while the return type
// is u32; a wider set needs a wider export. An empty declaration / zero bitmap
// is also a load-time error — a module with no handlers is permanently dead,
// and that must not pass installation.
//
// The SDK derives the bitmap from actual registrations; the host compares it
// with the manifest before enabling the plugin. This is not a dispatch input —
// run_hook never consults it.
type Hook int32

const (
	Hook_HOOK_UNSPECIFIED     Hook = 0
	Hook_HOOK_BEFORE_REQUEST  Hook = 1
	Hook_HOOK_AFTER_RESPONSE  Hook = 2
	Hook_HOOK_ON_STREAM_CHUNK Hook = 3
	Hook_HOOK_ON_HTTP_REQUEST Hook = 4
	Hook_HOOK_ON_TICK         Hook = 5
)

// Enum value maps for Hook.
var (
	Hook_name = map[int32]string{
		0: "HOOK_UNSPECIFIED",
		1: "HOOK_BEFORE_REQUEST",
		2: "HOOK_AFTER_RESPONSE",
		3: "HOOK_ON_STREAM_CHUNK",
		4: "HOOK_ON_HTTP_REQUEST",
		5: "HOOK_ON_TICK",
	}
	Hook_value = map[string]int32{
		"HOOK_UNSPECIFIED":     0,
		"HOOK_BEFORE_REQUEST":  1,
		"HOOK_AFTER_RESPONSE":  2,
		"HOOK_ON_STREAM_CHUNK": 3,
		"HOOK_ON_HTTP_REQUEST": 4,
		"HOOK_ON_TICK":         5,
	}
)

func (x Hook) Enum() *Hook {
	p := new(Hook)
	*p = x
	return p
}

func (x Hook) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hook) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torana_v2_torana_proto_enumTypes[0].Descriptor()
}

func (Hook) Type() protoreflect.EnumType {
	return &file_proto_torana_v2_torana_proto_enumTypes[0]
}

func (x Hook) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hook.Descriptor instead.
func (Hook) EnumDescriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{0}
}

// ErrorCode classifies a failed host call.
//
// v1 returned a bare string, and the same channel carried both the plugin's own
// stored data and the host's errors. Telling them apart took 55 lines of
// heuristics in the SDK whose own comment conceded the ambiguity was
// unresolvable. Notably, "the key is absent" and "durable state is not
// configured at all" were indistinguishable, so a plugin could not tell a fresh
// store from a disabled one.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// The capability was not granted. The plugin asked for something its manifest
	// may not even declare.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 1
	// The key, conversation or record does not exist.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 2
	// The feature exists but the operator has not configured it — no durable
	// state store, no offload provider, no pricing table.
	ErrorCode_ERROR_CODE_NOT_CONFIGURED ErrorCode = 3
	// Configured but not usable right now: upstream down, budget exhausted.
	ErrorCode_ERROR_CODE_UNAVAILABLE ErrorCode = 4
	// The plugin's arguments did not parse or did not make sense.
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 5
	// The host failed for a reason the plugin cannot act on.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_PERMISSION_DENIED",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_NOT_CONFIGURED",
		4: "ERROR_CODE_UNAVAILABLE",
		5: "ERROR_CODE_INVALID_ARGUMENT",
		6: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_PERMISSION_DENIED": 1,
		"ERROR_CODE_NOT_FOUND":         2,
		"ERROR_CODE_NOT_CONFIGURED":    3,
		"ERROR_CODE_UNAVAILABLE":       4,
		"ERROR_CODE_INVALID_ARGUMENT":  5,
		"ERROR_CODE_INTERNAL":          6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torana_v2_torana_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_torana_v2_torana_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{1}
}

// A single turn in a chat conversation.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// JSON array of multimodal parts (e.g. vision).
	ContentPartsJson  []byte      `protobuf:"bytes,3,opt,name=content_parts_json,json=contentPartsJson,proto3" json:"content_parts_json,omitempty"`
	Thinking          string      `protobuf:"bytes,4,opt,name=thinking,proto3" json:"thinking,omitempty"`
	ThinkingSignature string      `protobuf:"bytes,5,opt,name=thinking_signature,json=thinkingSignature,proto3" json:"thinking_signature,omitempty"`
	RedactedThinking  string      `protobuf:"bytes,6,opt,name=redacted_thinking,json=redactedThinking,proto3" json:"redacted_thinking,omitempty"`
	ToolCalls         []*ToolCall `protobuf:"bytes,7,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId        string      `protobuf:"bytes,8,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName          string      `protobuf:"bytes,9,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Opaque provider cache breakpoint on this message (JSON object, e.g.
	// Anthropic {"type":"ephemeral"}). Preserved verbatim across the plugin
	// boundary so mutating plugins don't strip prompt-cache markers.
	CacheControlJson []byte `protobuf:"bytes,10,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentPartsJson() []byte {
	if x != nil {
		return x.ContentPartsJson
	}
	return nil
}

func (x *Message) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *Message) GetThinkingSignature() string {
	if x != nil {
		return x.ThinkingSignature
	}
	return ""
}

func (x *Message) GetRedactedThinking() string {
	if x != nil {
		return x.RedactedThinking
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Message) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// An assistant's request to invoke a tool.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Verbatim JSON. Never decode and re-encode: key order is part of the
	// cacheable prefix.
	ArgumentsJson []byte `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Opaque provider token bound to this call (e.g. Gemini thoughtSignature).
	// Preserved across round-trips so replayed history keeps the model's
	// reasoning binding; empty for providers that don't emit one.
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *ToolCall) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// Describes a function available to the model.
type ToolDef struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Verbatim JSON Schema. Same rule as arguments_json.
	ParametersJson []byte `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Strict         bool   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	// Opaque cache breakpoint after this tool definition (JSON object).
	CacheControlJson []byte `protobuf:"bytes,5,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDef) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *ToolDef) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *ToolDef) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// Token accounting reported by the provider.
type Usage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InputTokens  int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// Input tokens served from the provider's prompt cache.
	CacheReadTokens int32 `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	// Input tokens written to the cache this turn; 0 if unreported.
	CacheWriteTokens int32 `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCacheReadTokens() int32 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *Usage) GetCacheWriteTokens() int32 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

// Canonical representation of a chat completion request.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,7,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	StopSequences []string               `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Unparsed provider fields, passed through transparently as JSON.
	ProviderExtensionsJson []byte `protobuf:"bytes,9,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	SafetySettingsJson     []byte `protobuf:"bytes,10,opt,name=safety_settings_json,json=safetySettingsJson,proto3" json:"safety_settings_json,omitempty"`
	// Proxy-internal metadata the host publishes to plugins: the routed provider,
	// the conversation id, the request path. Never serialized to the wire.
	//
	// In v1 this doubled as the channel plugins used to return verdicts, which is
	// why a plugin could block a request without holding the capability to block
	// — the host read the key long after it had lost track of who wrote it.
	// Verdicts are host calls in v2, so this is host-owned: a plugin changing it
	// is a protocol violation, not a grantable edit.
	ToranaMetaJson []byte `protobuf:"bytes,11,opt,name=torana_meta_json,json=toranaMetaJson,proto3" json:"torana_meta_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *ChatRequest) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

func (x *ChatRequest) GetSafetySettingsJson() []byte {
	if x != nil {
		return x.SafetySettingsJson
	}
	return nil
}

func (x *ChatRequest) GetToranaMetaJson() []byte {
	if x != nil {
		return x.ToranaMetaJson
	}
	return nil
}

// Canonical representation of a completed, non-streamed response.
//
// v1 had no such message. The response hook received a ChatRequest carrying,
// depending on which of three code paths produced it, a synthesized assistant
// message, the outbound request history, or nothing at all — a difference the
// plugin could not observe. Four independent auditors reported that as a bug.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model that actually answered, which may differ from the one requested.
	// Governed by ir.model.write.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Provider's response id, empty when it reported none.
	// Host-owned: forging it breaks correlation.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The assistant's turn. Governed by ir.messages.write.assistant.
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Governed by ir.messages.write.assistant (assistant-turn metadata).
	FinishReason string `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// Host-owned: forging usage forges the bill / observability.
	Usage *Usage `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	// Upstream HTTP status. Non-2xx responses reach observational hooks too.
	// Host-owned: host-measured fact.
	UpstreamStatus int32 `protobuf:"varint,6,opt,name=upstream_status,json=upstreamStatus,proto3" json:"upstream_status,omitempty"`
	// Host-owned: host-measured latency.
	DurationMs int64 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Provider fields Torana did not model, verbatim.
	// Governed by ir.params.write (same as request provider_extensions_json).
	ProviderExtensionsJson []byte `protobuf:"bytes,8,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{5}
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatResponse) GetUpstreamStatus() int32 {
	if x != nil {
		return x.UpstreamStatus
	}
	return 0
}

func (x *ChatResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ChatResponse) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

// Identifies the tool call a "tool_call" content block is assembling. Its
// arguments arrive as ToolCallDelta events between the block's start and stop.
type ToolCallRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque provider token on the call (Gemini thoughtSignature); empty otherwise.
	Signature     string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRef) Reset() {
	*x = ToolCallRef{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRef) ProtoMessage() {}

func (x *ToolCallRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRef.ProtoReflect.Descriptor instead.
func (*ToolCallRef) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCallRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallRef) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ToolCallDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ArgumentsDelta string                 `protobuf:"bytes,2,opt,name=arguments_delta,json=argumentsDelta,proto3" json:"arguments_delta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetArgumentsDelta() string {
	if x != nil {
		return x.ArgumentsDelta
	}
	return ""
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{8}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Structural boundaries in a streamed response.
//
// v1 emitted deltas and tool-call boundaries and nothing else, so a plugin that
// needed to know where a message or a content block began had to infer it from
// the delta sequence. Both stream plugins in the official set reimplemented that
// inference, ~60 lines each, and it is the single most copy-pasted thing a
// stream plugin does.
type MessageStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "assistant" for every provider Torana currently speaks, but carried rather
	// than assumed.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStart) Reset() {
	*x = MessageStart{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStart) ProtoMessage() {}

func (x *MessageStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStart.ProtoReflect.Descriptor instead.
func (*MessageStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{9}
}

func (x *MessageStart) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageStart) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// MessageStop closes the message and carries why it ended.
//
// finish_reason lives here rather than in an event of its own. v1 had a
// standalone finish_reason event, which would have left two ways to say the
// same thing — and one unambiguous representation per fact is the point of v2.
type MessageStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinishReason  string                 `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStop) Reset() {
	*x = MessageStop{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStop) ProtoMessage() {}

func (x *MessageStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStop.ProtoReflect.Descriptor instead.
func (*MessageStop) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{10}
}

func (x *MessageStop) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// A block carrying assistant text. Empty today; a message rather than a bare
// enum so it can gain fields without changing the oneof.
type TextBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBlock) Reset() {
	*x = TextBlock{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlock) ProtoMessage() {}

func (x *TextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlock.ProtoReflect.Descriptor instead.
func (*TextBlock) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{11}
}

// A block carrying extended thinking / reasoning text.
type ThinkingBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingBlock) Reset() {
	*x = ThinkingBlock{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingBlock) ProtoMessage() {}

func (x *ThinkingBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingBlock.ProtoReflect.Descriptor instead.
func (*ThinkingBlock) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{12}
}

// A block a provider emits that Torana does not model. The kind is passed
// through verbatim so a plugin written for that provider can still act on it.
type ProviderBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderBlock) Reset() {
	*x = ProviderBlock{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderBlock) ProtoMessage() {}

func (x *ProviderBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderBlock.ProtoReflect.Descriptor instead.
func (*ProviderBlock) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderBlock) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// ContentBlockStart opens a block. Deltas that follow belong to it until the
// matching stop.
//
// This is the ONLY block boundary. v1 had ToolCallStart/ToolCallEnd alongside
// nothing for text or thinking, so a plugin needed one mechanism for tool calls
// and inference for everything else. Folding every block in here means an
// assembler handles them all the same way.
//
// The kind is a oneof rather than a string with optional metadata beside it.
// A string would allow "tool_call" with no tool metadata, and "text" carrying
// some — contradictions a reader would have to know were impossible. A oneof
// makes them unrepresentable.
type ContentBlockStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlockStart_Text
	//	*ContentBlockStart_Thinking
	//	*ContentBlockStart_ToolCall
	//	*ContentBlockStart_Provider
	Block         isContentBlockStart_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStart) Reset() {
	*x = ContentBlockStart{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStart) ProtoMessage() {}

func (x *ContentBlockStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStart.ProtoReflect.Descriptor instead.
func (*ContentBlockStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{14}
}

func (x *ContentBlockStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ContentBlockStart) GetBlock() isContentBlockStart_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlockStart) GetText() *TextBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlockStart_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentBlockStart) GetThinking() *ThinkingBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlockStart_Thinking); ok {
			return x.Thinking
		}
	}
	return nil
}

func (x *ContentBlockStart) GetToolCall() *ToolCallRef {
	if x != nil {
		if x, ok := x.Block.(*ContentBlockStart_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ContentBlockStart) GetProvider() *ProviderBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlockStart_Provider); ok {
			return x.Provider
		}
	}
	return nil
}

type isContentBlockStart_Block interface {
	isContentBlockStart_Block()
}

type ContentBlockStart_Text struct {
	Text *TextBlock `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type ContentBlockStart_Thinking struct {
	Thinking *ThinkingBlock `protobuf:"bytes,3,opt,name=thinking,proto3,oneof"`
}

type ContentBlockStart_ToolCall struct {
	ToolCall *ToolCallRef `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ContentBlockStart_Provider struct {
	Provider *ProviderBlock `protobuf:"bytes,5,opt,name=provider,proto3,oneof"`
}

func (*ContentBlockStart_Text) isContentBlockStart_Block() {}

func (*ContentBlockStart_Thinking) isContentBlockStart_Block() {}

func (*ContentBlockStart_ToolCall) isContentBlockStart_Block() {}

func (*ContentBlockStart_Provider) isContentBlockStart_Block() {}

type ContentBlockStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStop) Reset() {
	*x = ContentBlockStop{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStop) ProtoMessage() {}

func (x *ContentBlockStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStop.ProtoReflect.Descriptor instead.
func (*ContentBlockStop) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{15}
}

func (x *ContentBlockStop) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// StreamEvent is one event in a streamed response.
//
// The canonical sequence, which adapters produce and plugins may rely on:
//
//	MessageStart{role, id, model}
//	  ContentBlockStart{index, text{} | thinking{}}
//	    TextDelta / ThinkingDelta ...
//	  ContentBlockStop{index}
//	  ContentBlockStart{index, tool_call{id, name}}
//	    ToolCallDelta{index, arguments_delta} ...
//	  ContentBlockStop{index}
//	Usage
//	MessageStop{finish_reason}
//
// Usage may arrive before or after MessageStop depending on the provider, and
// StreamError may replace the remainder at any point. Everything else is
// ordered as shown, and every block is opened and closed exactly once.
type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Outbound mutations of these variants are governed by the cross-hook write
	// grants (see capabilities_outbound.go): assistant content by
	// ir.messages.write.assistant, structural ops / Suppress / StreamError by
	// ir.stream.write, MessageStart.model by ir.model.write. usage is host-owned.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_TextDelta
	//	*StreamEvent_ThinkingDelta
	//	*StreamEvent_ToolCallDelta
	//	*StreamEvent_Usage
	//	*StreamEvent_Error
	//	*StreamEvent_SignatureDelta
	//	*StreamEvent_MessageStart
	//	*StreamEvent_MessageStop
	//	*StreamEvent_ContentBlockStart
	//	*StreamEvent_ContentBlockStop
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{16}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetTextDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetThinkingDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *StreamEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamEvent) GetSignatureDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_SignatureDelta); ok {
			return x.SignatureDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetMessageStart() *MessageStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStart); ok {
			return x.MessageStart
		}
	}
	return nil
}

func (x *StreamEvent) GetMessageStop() *MessageStop {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStop); ok {
			return x.MessageStop
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStart() *ContentBlockStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStart); ok {
			return x.ContentBlockStart
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStop() *ContentBlockStop {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStop); ok {
			return x.ContentBlockStop
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_TextDelta struct {
	TextDelta string `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type StreamEvent_ThinkingDelta struct {
	ThinkingDelta string `protobuf:"bytes,2,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type StreamEvent_ToolCallDelta struct {
	ToolCallDelta *ToolCallDelta `protobuf:"bytes,3,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type StreamEvent_Usage struct {
	Usage *Usage `protobuf:"bytes,4,opt,name=usage,proto3,oneof"`
}

type StreamEvent_Error struct {
	Error *StreamError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type StreamEvent_SignatureDelta struct {
	// Opaque provider signature paired with the surrounding block (Gemini
	// thoughtSignature on a standalone text/thought part).
	SignatureDelta string `protobuf:"bytes,6,opt,name=signature_delta,json=signatureDelta,proto3,oneof"`
}

type StreamEvent_MessageStart struct {
	MessageStart *MessageStart `protobuf:"bytes,7,opt,name=message_start,json=messageStart,proto3,oneof"`
}

type StreamEvent_MessageStop struct {
	MessageStop *MessageStop `protobuf:"bytes,8,opt,name=message_stop,json=messageStop,proto3,oneof"`
}

type StreamEvent_ContentBlockStart struct {
	ContentBlockStart *ContentBlockStart `protobuf:"bytes,9,opt,name=content_block_start,json=contentBlockStart,proto3,oneof"`
}

type StreamEvent_ContentBlockStop struct {
	ContentBlockStop *ContentBlockStop `protobuf:"bytes,10,opt,name=content_block_stop,json=contentBlockStop,proto3,oneof"`
}

func (*StreamEvent_TextDelta) isStreamEvent_Event() {}

func (*StreamEvent_ThinkingDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallDelta) isStreamEvent_Event() {}

func (*StreamEvent_Usage) isStreamEvent_Event() {}

func (*StreamEvent_Error) isStreamEvent_Event() {}

func (*StreamEvent_SignatureDelta) isStreamEvent_Event() {}

func (*StreamEvent_MessageStart) isStreamEvent_Event() {}

func (*StreamEvent_MessageStop) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStart) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStop) isStreamEvent_Event() {}

// StreamEvents exists because a protobuf oneof cannot hold a repeated field.
type StreamEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StreamEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvents) Reset() {
	*x = StreamEvents{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvents) ProtoMessage() {}

func (x *StreamEvents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvents.ProtoReflect.Descriptor instead.
func (*StreamEvents) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEvents) GetEvents() []*StreamEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Incoming HTTP request forwarded to a plugin's run_on_http_request hook.
// Built directly from net/http — does not cross the chat IR.
type HttpRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Raw query string, without the leading "?". v1 dropped this entirely, so a
	// plugin serving a page could not read its own query parameters.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// "http" or "https".
	Scheme string `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Caller address, for a plugin that wants to refuse non-local requests
	// itself. The host has already applied its own guard before dispatching.
	RemoteAddr string `protobuf:"bytes,5,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// JSON-encoded map of request headers (map[string][]string), filtered by the
	// host to the same allowlist the chat path uses.
	HeadersJson   []byte `protobuf:"bytes,6,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{18}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HttpRequest) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Response produced by a plugin's run_on_http_request hook.
type HttpResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// JSON-encoded map of response headers (map[string][]string). The host
	// applies its own allowlist; anything outside it fails the response.
	HeadersJson   []byte `protobuf:"bytes,2,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{19}
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Fired periodically by the host, with no request in flight.
//
// Every other hook is reactive: a plugin can only act while a request is
// passing through it. This one exists so a plugin can act when nothing is
// happening — refreshing a provider cache before it lapses, emitting a periodic
// report, expiring its own state.
//
// Requires env.background_tick. Running code with no request in flight is a
// capability an operator should grant deliberately: a plugin holding it can act
// — and spend — outside any request the operator can see.
//
// HookInput.request_id on a tick is a synthetic execution-scope id for
// plugin-private ephemeral metadata (env.meta_*), discarded when the tick
// ends — not a caller request. Caller content remains unavailable.
type TickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing within one scheduler, starting at 1. Resets if the
	// scheduler restarts, so treat it as an ordering hint rather than a durable
	// counter.
	TickId uint64 `protobuf:"varint,1,opt,name=tick_id,json=tickId,proto3" json:"tick_id,omitempty"`
	// Host wall-clock time. Plugins have no clock of their own: WASI preview1
	// exposes none, and this is the only time source they get.
	UnixMillis int64 `protobuf:"varint,2,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	// Configured interval, so a plugin can reason about elapsed time without
	// assuming a particular cadence.
	IntervalMs    int64 `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{20}
}

func (x *TickRequest) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

func (x *TickRequest) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *TickRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// What a plugin did during a tick. Reported for observability only; the host
// attaches no meaning to it.
type TickOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       int32                  `protobuf:"varint,1,opt,name=actions,proto3" json:"actions,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickOutcome) Reset() {
	*x = TickOutcome{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickOutcome) ProtoMessage() {}

func (x *TickOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickOutcome.ProtoReflect.Descriptor instead.
func (*TickOutcome) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{21}
}

func (x *TickOutcome) GetActions() int32 {
	if x != nil {
		return x.Actions
	}
	return 0
}

func (x *TickOutcome) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// AfterResponse is the payload for the after-response hook.
//
// mutable lives here, not on HookInput, because only this path can be
// observational. False when the response was streamed or was an upstream
// error: the bytes have already gone to the caller, or there is no body to
// rewrite, so a returned replacement is discarded. Every other hook is always
// mutable — putting a flag on the global envelope let a before-request or
// stream dispatch claim otherwise, which is nonsense.
//
// v1 offered no such signal, so a plugin learned its mutations were being
// discarded only by their having no effect.
type AfterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *ChatResponse          `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Mutable       bool                   `protobuf:"varint,2,opt,name=mutable,proto3" json:"mutable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterResponse) Reset() {
	*x = AfterResponse{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterResponse) ProtoMessage() {}

func (x *AfterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterResponse.ProtoReflect.Descriptor instead.
func (*AfterResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{22}
}

func (x *AfterResponse) GetResponse() *ChatResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AfterResponse) GetMutable() bool {
	if x != nil {
		return x.Mutable
	}
	return false
}

// HookInput is what every hook receives. The payload determines which hook this
// is; there is no separate hook field to contradict it. The guest receives it
// via run_hook(ptr, size) -> u64 — one export, no request_id WASM argument.
type HookInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minor version of the v2 contract the host is speaking. Additive changes
	// bump this; a plugin may use it to detect fields it can rely on.
	AbiMinor uint32 `protobuf:"varint,1,opt,name=abi_minor,json=abiMinor,proto3" json:"abi_minor,omitempty"`
	// Host-assigned execution-scope id. This is the only place the id appears —
	// it is not also a WASM argument.
	//
	// For request-scoped hooks (before_request, after_response, stream, http)
	// this identifies the caller request, and all stream events for one response
	// share it. Availability of request-derived host calls is defined per
	// command and hook; the ID alone grants or guarantees nothing.
	//
	// For ticks — which fire with no request in flight — the host supplies a
	// unique synthetic scope id. Plugin-private ephemeral metadata (env.meta_*)
	// is available inside that scope and is discarded when the tick ends; that
	// is why the id must be unique and must not reuse a live request's. Caller
	// content and identity remain unavailable: there is no caller. Authors must
	// not interpret a tick's request_id as a caller request.
	RequestId uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HookInput_ChatRequest
	//	*HookInput_AfterResponse
	//	*HookInput_StreamEvent
	//	*HookInput_HttpRequest
	//	*HookInput_TickRequest
	Payload       isHookInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookInput) Reset() {
	*x = HookInput{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookInput) ProtoMessage() {}

func (x *HookInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookInput.ProtoReflect.Descriptor instead.
func (*HookInput) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{23}
}

func (x *HookInput) GetAbiMinor() uint32 {
	if x != nil {
		return x.AbiMinor
	}
	return 0
}

func (x *HookInput) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HookInput) GetPayload() isHookInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookInput) GetChatRequest() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_ChatRequest); ok {
			return x.ChatRequest
		}
	}
	return nil
}

func (x *HookInput) GetAfterResponse() *AfterResponse {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_AfterResponse); ok {
			return x.AfterResponse
		}
	}
	return nil
}

func (x *HookInput) GetStreamEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_StreamEvent); ok {
			return x.StreamEvent
		}
	}
	return nil
}

func (x *HookInput) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *HookInput) GetTickRequest() *TickRequest {
	if x != nil {
		if x, ok := x.Payload.(*HookInput_TickRequest); ok {
			return x.TickRequest
		}
	}
	return nil
}

type isHookInput_Payload interface {
	isHookInput_Payload()
}

type HookInput_ChatRequest struct {
	ChatRequest *ChatRequest `protobuf:"bytes,4,opt,name=chat_request,json=chatRequest,proto3,oneof"`
}

type HookInput_AfterResponse struct {
	AfterResponse *AfterResponse `protobuf:"bytes,5,opt,name=after_response,json=afterResponse,proto3,oneof"`
}

type HookInput_StreamEvent struct {
	StreamEvent *StreamEvent `protobuf:"bytes,6,opt,name=stream_event,json=streamEvent,proto3,oneof"`
}

type HookInput_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,7,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type HookInput_TickRequest struct {
	TickRequest *TickRequest `protobuf:"bytes,8,opt,name=tick_request,json=tickRequest,proto3,oneof"`
}

func (*HookInput_ChatRequest) isHookInput_Payload() {}

func (*HookInput_AfterResponse) isHookInput_Payload() {}

func (*HookInput_StreamEvent) isHookInput_Payload() {}

func (*HookInput_HttpRequest) isHookInput_Payload() {}

func (*HookInput_TickRequest) isHookInput_Payload() {}

// Suppress drops the input event and emits nothing. Stream hooks only.
//
// An empty message inside a oneof still marshals to a tag and a zero length, so
// this is distinguishable on the wire from a plugin that returned nothing —
// which is what makes it safe to express suppression as an action rather than
// as a flag.
type Suppress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suppress) Reset() {
	*x = Suppress{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suppress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suppress) ProtoMessage() {}

func (x *Suppress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suppress.ProtoReflect.Descriptor instead.
func (*Suppress) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{24}
}

// HookResult is what a hook returns when it wants something done.
//
// There is exactly ONE axis: the action. An earlier draft had two — a
// disposition enum beside a payload oneof — which made five illegal
// combinations representable: PASS carrying a payload, REPLACE carrying none,
// SUPPRESS carrying events, SUPPRESS on a non-stream hook, and an unspecified
// disposition. The validator caught them, but a shape that cannot express them
// needs no validator.
//
// Worse, the two-axis form claimed something it could not enforce. A frame with
// an unspecified disposition marshals to zero bytes, and zero bytes IS
// pass-through at the ABI level — a length, not a message — so the host never
// saw a frame to reject. The rule was unreachable.
//
// Pass-through therefore has exactly one encoding: return zero bytes. A
// HookResult with no action set marshals to zero bytes too, so the two are the
// same thing rather than two spellings of it.
//
// The action's type must match the hook that was dispatched. A result carrying
// another hook's action is a protocol error, and that one IS enforceable
// because such a frame is not empty.
type HookResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*HookResult_ReplaceRequest
	//	*HookResult_ReplaceResponse
	//	*HookResult_EmitEvents
	//	*HookResult_ServeHttp
	//	*HookResult_TickOutcome
	//	*HookResult_Suppress
	Action        isHookResult_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{25}
}

func (x *HookResult) GetAction() isHookResult_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *HookResult) GetReplaceRequest() *ChatRequest {
	if x != nil {
		if x, ok := x.Action.(*HookResult_ReplaceRequest); ok {
			return x.ReplaceRequest
		}
	}
	return nil
}

func (x *HookResult) GetReplaceResponse() *ChatResponse {
	if x != nil {
		if x, ok := x.Action.(*HookResult_ReplaceResponse); ok {
			return x.ReplaceResponse
		}
	}
	return nil
}

func (x *HookResult) GetEmitEvents() *StreamEvents {
	if x != nil {
		if x, ok := x.Action.(*HookResult_EmitEvents); ok {
			return x.EmitEvents
		}
	}
	return nil
}

func (x *HookResult) GetServeHttp() *HttpResponse {
	if x != nil {
		if x, ok := x.Action.(*HookResult_ServeHttp); ok {
			return x.ServeHttp
		}
	}
	return nil
}

func (x *HookResult) GetTickOutcome() *TickOutcome {
	if x != nil {
		if x, ok := x.Action.(*HookResult_TickOutcome); ok {
			return x.TickOutcome
		}
	}
	return nil
}

func (x *HookResult) GetSuppress() *Suppress {
	if x != nil {
		if x, ok := x.Action.(*HookResult_Suppress); ok {
			return x.Suppress
		}
	}
	return nil
}

type isHookResult_Action interface {
	isHookResult_Action()
}

type HookResult_ReplaceRequest struct {
	ReplaceRequest *ChatRequest `protobuf:"bytes,1,opt,name=replace_request,json=replaceRequest,proto3,oneof"`
}

type HookResult_ReplaceResponse struct {
	ReplaceResponse *ChatResponse `protobuf:"bytes,2,opt,name=replace_response,json=replaceResponse,proto3,oneof"`
}

type HookResult_EmitEvents struct {
	EmitEvents *StreamEvents `protobuf:"bytes,3,opt,name=emit_events,json=emitEvents,proto3,oneof"`
}

type HookResult_ServeHttp struct {
	ServeHttp *HttpResponse `protobuf:"bytes,4,opt,name=serve_http,json=serveHttp,proto3,oneof"`
}

type HookResult_TickOutcome struct {
	TickOutcome *TickOutcome `protobuf:"bytes,5,opt,name=tick_outcome,json=tickOutcome,proto3,oneof"`
}

type HookResult_Suppress struct {
	Suppress *Suppress `protobuf:"bytes,6,opt,name=suppress,proto3,oneof"`
}

func (*HookResult_ReplaceRequest) isHookResult_Action() {}

func (*HookResult_ReplaceResponse) isHookResult_Action() {}

func (*HookResult_EmitEvents) isHookResult_Action() {}

func (*HookResult_ServeHttp) isHookResult_Action() {}

func (*HookResult_TickOutcome) isHookResult_Action() {}

func (*HookResult_Suppress) isHookResult_Action() {}

type HostError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=torana.v2.ErrorCode" json:"code,omitempty"`
	// Human-readable, for logs. Plugins should branch on `code`, never on this.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostError) Reset() {
	*x = HostError{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostError) ProtoMessage() {}

func (x *HostError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostError.ProtoReflect.Descriptor instead.
func (*HostError) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{26}
}

func (x *HostError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *HostError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HostCallResult is what every host call returns.
//
// A successful call with no value sets `value` to empty bytes, which is
// distinguishable from an error — unlike v1, where an empty string meant
// "granted but no value", "cache miss", "key absent", "feature unconfigured",
// and "the host refused to write an empty payload", all at once.
type HostCallResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*HostCallResult_Value
	//	*HostCallResult_Error
	Result        isHostCallResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCallResult) Reset() {
	*x = HostCallResult{}
	mi := &file_proto_torana_v2_torana_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallResult) ProtoMessage() {}

func (x *HostCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v2_torana_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallResult.ProtoReflect.Descriptor instead.
func (*HostCallResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v2_torana_proto_rawDescGZIP(), []int{27}
}

func (x *HostCallResult) GetResult() isHostCallResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HostCallResult) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*HostCallResult_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *HostCallResult) GetError() *HostError {
	if x != nil {
		if x, ok := x.Result.(*HostCallResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isHostCallResult_Result interface {
	isHostCallResult_Result()
}

type HostCallResult_Value struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type HostCallResult_Error struct {
	Error *HostError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*HostCallResult_Value) isHostCallResult_Result() {}

func (*HostCallResult_Error) isHostCallResult_Result() {}

var File_proto_torana_v2_torana_proto protoreflect.FileDescriptor

const file_proto_torana_v2_torana_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/torana/v2/torana.proto\x12\ttorana.v2\"\xfe\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x12content_parts_json\x18\x03 \x01(\fR\x10contentPartsJson\x12\x1a\n" +
	"\bthinking\x18\x04 \x01(\tR\bthinking\x12-\n" +
	"\x12thinking_signature\x18\x05 \x01(\tR\x11thinkingSignature\x12+\n" +
	"\x11redacted_thinking\x18\x06 \x01(\tR\x10redactedThinking\x122\n" +
	"\n" +
	"tool_calls\x18\a \x03(\v2\x13.torana.v2.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\b \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\t \x01(\tR\btoolName\x12,\n" +
	"\x12cache_control_json\x18\n" +
	" \x01(\fR\x10cacheControlJson\"s\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xae\x01\n" +
	"\aToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\fR\x0eparametersJson\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\x12,\n" +
	"\x12cache_control_json\x18\x05 \x01(\fR\x10cacheControlJson\"\xa9\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x05R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x05R\x10cacheWriteTokens\"\xe0\x03\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.torana.v2.MessageR\bmessages\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.torana.v2.ToolDefR\x05tools\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\"\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x01H\x01R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\a \x01(\x01H\x02R\x04topP\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x128\n" +
	"\x18provider_extensions_json\x18\t \x01(\fR\x16providerExtensionsJson\x120\n" +
	"\x14safety_settings_json\x18\n" +
	" \x01(\fR\x12safetySettingsJson\x12(\n" +
	"\x10torana_meta_json\x18\v \x01(\fR\x0etoranaMetaJsonB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_p\"\xb3\x02\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12,\n" +
	"\amessage\x18\x03 \x01(\v2\x12.torana.v2.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12&\n" +
	"\x05usage\x18\x05 \x01(\v2\x10.torana.v2.UsageR\x05usage\x12'\n" +
	"\x0fupstream_status\x18\x06 \x01(\x05R\x0eupstreamStatus\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x128\n" +
	"\x18provider_extensions_json\x18\b \x01(\fR\x16providerExtensionsJson\"O\n" +
	"\vToolCallRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"N\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12'\n" +
	"\x0farguments_delta\x18\x02 \x01(\tR\x0eargumentsDelta\";\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\fMessageStart\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"2\n" +
	"\vMessageStop\x12#\n" +
	"\rfinish_reason\x18\x01 \x01(\tR\ffinishReason\"\v\n" +
	"\tTextBlock\"\x0f\n" +
	"\rThinkingBlock\"#\n" +
	"\rProviderBlock\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x85\x02\n" +
	"\x11ContentBlockStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12*\n" +
	"\x04text\x18\x02 \x01(\v2\x14.torana.v2.TextBlockH\x00R\x04text\x126\n" +
	"\bthinking\x18\x03 \x01(\v2\x18.torana.v2.ThinkingBlockH\x00R\bthinking\x125\n" +
	"\ttool_call\x18\x04 \x01(\v2\x16.torana.v2.ToolCallRefH\x00R\btoolCall\x126\n" +
	"\bprovider\x18\x05 \x01(\v2\x18.torana.v2.ProviderBlockH\x00R\bproviderB\a\n" +
	"\x05block\"(\n" +
	"\x10ContentBlockStop\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"\xc3\x04\n" +
	"\vStreamEvent\x12\x1f\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tH\x00R\ttextDelta\x12'\n" +
	"\x0ethinking_delta\x18\x02 \x01(\tH\x00R\rthinkingDelta\x12B\n" +
	"\x0ftool_call_delta\x18\x03 \x01(\v2\x18.torana.v2.ToolCallDeltaH\x00R\rtoolCallDelta\x12(\n" +
	"\x05usage\x18\x04 \x01(\v2\x10.torana.v2.UsageH\x00R\x05usage\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x16.torana.v2.StreamErrorH\x00R\x05error\x12)\n" +
	"\x0fsignature_delta\x18\x06 \x01(\tH\x00R\x0esignatureDelta\x12>\n" +
	"\rmessage_start\x18\a \x01(\v2\x17.torana.v2.MessageStartH\x00R\fmessageStart\x12;\n" +
	"\fmessage_stop\x18\b \x01(\v2\x16.torana.v2.MessageStopH\x00R\vmessageStop\x12N\n" +
	"\x13content_block_start\x18\t \x01(\v2\x1c.torana.v2.ContentBlockStartH\x00R\x11contentBlockStart\x12K\n" +
	"\x12content_block_stop\x18\n" +
	" \x01(\v2\x1b.torana.v2.ContentBlockStopH\x00R\x10contentBlockStopB\a\n" +
	"\x05event\">\n" +
	"\fStreamEvents\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.torana.v2.StreamEventR\x06events\"\xbf\x01\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x1f\n" +
	"\vremote_addr\x18\x05 \x01(\tR\n" +
	"remoteAddr\x12!\n" +
	"\fheaders_json\x18\x06 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\"]\n" +
	"\fHttpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12!\n" +
	"\fheaders_json\x18\x02 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"h\n" +
	"\vTickRequest\x12\x17\n" +
	"\atick_id\x18\x01 \x01(\x04R\x06tickId\x12\x1f\n" +
	"\vunix_millis\x18\x02 \x01(\x03R\n" +
	"unixMillis\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x03R\n" +
	"intervalMs\";\n" +
	"\vTickOutcome\x12\x18\n" +
	"\aactions\x18\x01 \x01(\x05R\aactions\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"^\n" +
	"\rAfterResponse\x123\n" +
	"\bresponse\x18\x01 \x01(\v2\x17.torana.v2.ChatResponseR\bresponse\x12\x18\n" +
	"\amutable\x18\x02 \x01(\bR\amutable\"\x89\x03\n" +
	"\tHookInput\x12\x1b\n" +
	"\tabi_minor\x18\x01 \x01(\rR\babiMinor\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12;\n" +
	"\fchat_request\x18\x04 \x01(\v2\x16.torana.v2.ChatRequestH\x00R\vchatRequest\x12A\n" +
	"\x0eafter_response\x18\x05 \x01(\v2\x18.torana.v2.AfterResponseH\x00R\rafterResponse\x12;\n" +
	"\fstream_event\x18\x06 \x01(\v2\x16.torana.v2.StreamEventH\x00R\vstreamEvent\x12;\n" +
	"\fhttp_request\x18\a \x01(\v2\x16.torana.v2.HttpRequestH\x00R\vhttpRequest\x12;\n" +
	"\ftick_request\x18\b \x01(\v2\x16.torana.v2.TickRequestH\x00R\vtickRequestB\t\n" +
	"\apayload\"\n" +
	"\n" +
	"\bSuppress\"\x85\x03\n" +
	"\n" +
	"HookResult\x12A\n" +
	"\x0freplace_request\x18\x01 \x01(\v2\x16.torana.v2.ChatRequestH\x00R\x0ereplaceRequest\x12D\n" +
	"\x10replace_response\x18\x02 \x01(\v2\x17.torana.v2.ChatResponseH\x00R\x0freplaceResponse\x12:\n" +
	"\vemit_events\x18\x03 \x01(\v2\x17.torana.v2.StreamEventsH\x00R\n" +
	"emitEvents\x128\n" +
	"\n" +
	"serve_http\x18\x04 \x01(\v2\x17.torana.v2.HttpResponseH\x00R\tserveHttp\x12;\n" +
	"\ftick_outcome\x18\x05 \x01(\v2\x16.torana.v2.TickOutcomeH\x00R\vtickOutcome\x121\n" +
	"\bsuppress\x18\x06 \x01(\v2\x13.torana.v2.SuppressH\x00R\bsuppressB\b\n" +
	"\x06action\"O\n" +
	"\tHostError\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.torana.v2.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\x0eHostCallResult\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x14.torana.v2.HostErrorH\x00R\x05errorB\b\n" +
	"\x06result*\x94\x01\n" +
	"\x04Hook\x12\x14\n" +
	"\x10HOOK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13HOOK_BEFORE_REQUEST\x10\x01\x12\x17\n" +
	"\x13HOOK_AFTER_RESPONSE\x10\x02\x12\x18\n" +
	"\x14HOOK_ON_STREAM_CHUNK\x10\x03\x12\x18\n" +
	"\x14HOOK_ON_HTTP_REQUEST\x10\x04\x12\x10\n" +
	"\fHOOK_ON_TICK\x10\x05*\xd8\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_NOT_CONFIGURED\x10\x03\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x04\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x06B0Z.github.com/torana-edge/torana-plugin-sdk/pb/v2b\x06proto3"

var (
	file_proto_torana_v2_torana_proto_rawDescOnce sync.Once
	file_proto_torana_v2_torana_proto_rawDescData []byte
)

func file_proto_torana_v2_torana_proto_rawDescGZIP() []byte {
	file_proto_torana_v2_torana_proto_rawDescOnce.Do(func() {
		file_proto_torana_v2_torana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torana_v2_torana_proto_rawDesc), len(file_proto_torana_v2_torana_proto_rawDesc)))
	})
	return file_proto_torana_v2_torana_proto_rawDescData
}

var file_proto_torana_v2_torana_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_torana_v2_torana_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_torana_v2_torana_proto_goTypes = []any{
	(Hook)(0),                 // 0: torana.v2.Hook
	(ErrorCode)(0),            // 1: torana.v2.ErrorCode
	(*Message)(nil),           // 2: torana.v2.Message
	(*ToolCall)(nil),          // 3: torana.v2.ToolCall
	(*ToolDef)(nil),           // 4: torana.v2.ToolDef
	(*Usage)(nil),             // 5: torana.v2.Usage
	(*ChatRequest)(nil),       // 6: torana.v2.ChatRequest
	(*ChatResponse)(nil),      // 7: torana.v2.ChatResponse
	(*ToolCallRef)(nil),       // 8: torana.v2.ToolCallRef
	(*ToolCallDelta)(nil),     // 9: torana.v2.ToolCallDelta
	(*StreamError)(nil),       // 10: torana.v2.StreamError
	(*MessageStart)(nil),      // 11: torana.v2.MessageStart
	(*MessageStop)(nil),       // 12: torana.v2.MessageStop
	(*TextBlock)(nil),         // 13: torana.v2.TextBlock
	(*ThinkingBlock)(nil),     // 14: torana.v2.ThinkingBlock
	(*ProviderBlock)(nil),     // 15: torana.v2.ProviderBlock
	(*ContentBlockStart)(nil), // 16: torana.v2.ContentBlockStart
	(*ContentBlockStop)(nil),  // 17: torana.v2.ContentBlockStop
	(*StreamEvent)(nil),       // 18: torana.v2.StreamEvent
	(*StreamEvents)(nil),      // 19: torana.v2.StreamEvents
	(*HttpRequest)(nil),       // 20: torana.v2.HttpRequest
	(*HttpResponse)(nil),      // 21: torana.v2.HttpResponse
	(*TickRequest)(nil),       // 22: torana.v2.TickRequest
	(*TickOutcome)(nil),       // 23: torana.v2.TickOutcome
	(*AfterResponse)(nil),     // 24: torana.v2.AfterResponse
	(*HookInput)(nil),         // 25: torana.v2.HookInput
	(*Suppress)(nil),          // 26: torana.v2.Suppress
	(*HookResult)(nil),        // 27: torana.v2.HookResult
	(*HostError)(nil),         // 28: torana.v2.HostError
	(*HostCallResult)(nil),    // 29: torana.v2.HostCallResult
}
var file_proto_torana_v2_torana_proto_depIdxs = []int32{
	3,  // 0: torana.v2.Message.tool_calls:type_name -> torana.v2.ToolCall
	2,  // 1: torana.v2.ChatRequest.messages:type_name -> torana.v2.Message
	4,  // 2: torana.v2.ChatRequest.tools:type_name -> torana.v2.ToolDef
	2,  // 3: torana.v2.ChatResponse.message:type_name -> torana.v2.Message
	5,  // 4: torana.v2.ChatResponse.usage:type_name -> torana.v2.Usage
	13, // 5: torana.v2.ContentBlockStart.text:type_name -> torana.v2.TextBlock
	14, // 6: torana.v2.ContentBlockStart.thinking:type_name -> torana.v2.ThinkingBlock
	8,  // 7: torana.v2.ContentBlockStart.tool_call:type_name -> torana.v2.ToolCallRef
	15, // 8: torana.v2.ContentBlockStart.provider:type_name -> torana.v2.ProviderBlock
	9,  // 9: torana.v2.StreamEvent.tool_call_delta:type_name -> torana.v2.ToolCallDelta
	5,  // 10: torana.v2.StreamEvent.usage:type_name -> torana.v2.Usage
	10, // 11: torana.v2.StreamEvent.error:type_name -> torana.v2.StreamError
	11, // 12: torana.v2.StreamEvent.message_start:type_name -> torana.v2.MessageStart
	12, // 13: torana.v2.StreamEvent.message_stop:type_name -> torana.v2.MessageStop
	16, // 14: torana.v2.StreamEvent.content_block_start:type_name -> torana.v2.ContentBlockStart
	17, // 15: torana.v2.StreamEvent.content_block_stop:type_name -> torana.v2.ContentBlockStop
	18, // 16: torana.v2.StreamEvents.events:type_name -> torana.v2.StreamEvent
	7,  // 17: torana.v2.AfterResponse.response:type_name -> torana.v2.ChatResponse
	6,  // 18: torana.v2.HookInput.chat_request:type_name -> torana.v2.ChatRequest
	24, // 19: torana.v2.HookInput.after_response:type_name -> torana.v2.AfterResponse
	18, // 20: torana.v2.HookInput.stream_event:type_name -> torana.v2.StreamEvent
	20, // 21: torana.v2.HookInput.http_request:type_name -> torana.v2.HttpRequest
	22, // 22: torana.v2.HookInput.tick_request:type_name -> torana.v2.TickRequest
	6,  // 23: torana.v2.HookResult.replace_request:type_name -> torana.v2.ChatRequest
	7,  // 24: torana.v2.HookResult.replace_response:type_name -> torana.v2.ChatResponse
	19, // 25: torana.v2.HookResult.emit_events:type_name -> torana.v2.StreamEvents
	21, // 26: torana.v2.HookResult.serve_http:type_name -> torana.v2.HttpResponse
	23, // 27: torana.v2.HookResult.tick_outcome:type_name -> torana.v2.TickOutcome
	26, // 28: torana.v2.HookResult.suppress:type_name -> torana.v2.Suppress
	1,  // 29: torana.v2.HostError.code:type_name -> torana.v2.ErrorCode
	28, // 30: torana.v2.HostCallResult.error:type_name -> torana.v2.HostError
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_torana_v2_torana_proto_init() }
func file_proto_torana_v2_torana_proto_init() {
	if File_proto_torana_v2_torana_proto != nil {
		return
	}
	file_proto_torana_v2_torana_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_torana_v2_torana_proto_msgTypes[14].OneofWrappers = []any{
		(*ContentBlockStart_Text)(nil),
		(*ContentBlockStart_Thinking)(nil),
		(*ContentBlockStart_ToolCall)(nil),
		(*ContentBlockStart_Provider)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[16].OneofWrappers = []any{
		(*StreamEvent_TextDelta)(nil),
		(*StreamEvent_ThinkingDelta)(nil),
		(*StreamEvent_ToolCallDelta)(nil),
		(*StreamEvent_Usage)(nil),
		(*StreamEvent_Error)(nil),
		(*StreamEvent_SignatureDelta)(nil),
		(*StreamEvent_MessageStart)(nil),
		(*StreamEvent_MessageStop)(nil),
		(*StreamEvent_ContentBlockStart)(nil),
		(*StreamEvent_ContentBlockStop)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[23].OneofWrappers = []any{
		(*HookInput_ChatRequest)(nil),
		(*HookInput_AfterResponse)(nil),
		(*HookInput_StreamEvent)(nil),
		(*HookInput_HttpRequest)(nil),
		(*HookInput_TickRequest)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[25].OneofWrappers = []any{
		(*HookResult_ReplaceRequest)(nil),
		(*HookResult_ReplaceResponse)(nil),
		(*HookResult_EmitEvents)(nil),
		(*HookResult_ServeHttp)(nil),
		(*HookResult_TickOutcome)(nil),
		(*HookResult_Suppress)(nil),
	}
	file_proto_torana_v2_torana_proto_msgTypes[27].OneofWrappers = []any{
		(*HostCallResult_Value)(nil),
		(*HostCallResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torana_v2_torana_proto_rawDesc), len(file_proto_torana_v2_torana_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_torana_v2_torana_proto_goTypes,
		DependencyIndexes: file_proto_torana_v2_torana_proto_depIdxs,
		EnumInfos:         file_proto_torana_v2_torana_proto_enumTypes,
		MessageInfos:      file_proto_torana_v2_torana_proto_msgTypes,
	}.Build()
	File_proto_torana_v2_torana_proto = out.File
	file_proto_torana_v2_torana_proto_goTypes = nil
	file_proto_torana_v2_torana_proto_depIdxs = nil
}
