// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/torana/v1/torana.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single turn in a chat conversation.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// JSON array of multimodal parts (e.g. vision)
	ContentPartsJson  []byte      `protobuf:"bytes,3,opt,name=content_parts_json,json=contentPartsJson,proto3" json:"content_parts_json,omitempty"`
	Thinking          string      `protobuf:"bytes,4,opt,name=thinking,proto3" json:"thinking,omitempty"`
	ThinkingSignature string      `protobuf:"bytes,5,opt,name=thinking_signature,json=thinkingSignature,proto3" json:"thinking_signature,omitempty"`
	RedactedThinking  string      `protobuf:"bytes,9,opt,name=redacted_thinking,json=redactedThinking,proto3" json:"redacted_thinking,omitempty"`
	ToolCalls         []*ToolCall `protobuf:"bytes,6,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId        string      `protobuf:"bytes,7,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName          string      `protobuf:"bytes,8,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Opaque provider cache breakpoint on this message (JSON object, e.g.
	// Anthropic {"type":"ephemeral"}). Preserved verbatim across the plugin
	// boundary so mutating plugins don't strip prompt-cache markers.
	CacheControlJson []byte `protobuf:"bytes,10,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentPartsJson() []byte {
	if x != nil {
		return x.ContentPartsJson
	}
	return nil
}

func (x *Message) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *Message) GetThinkingSignature() string {
	if x != nil {
		return x.ThinkingSignature
	}
	return ""
}

func (x *Message) GetRedactedThinking() string {
	if x != nil {
		return x.RedactedThinking
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Message) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// An assistant's request to invoke a tool.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson []byte                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Opaque provider token bound to this call (e.g. Gemini thoughtSignature).
	// Preserved across round-trips so replayed history keeps the model's
	// reasoning binding; empty for providers that don't emit one.
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *ToolCall) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// Describes a function available to the model.
type ToolDef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson []byte                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	Strict         bool                   `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	// Opaque cache breakpoint after this tool definition (JSON object).
	CacheControlJson []byte `protobuf:"bytes,5,opt,name=cache_control_json,json=cacheControlJson,proto3" json:"cache_control_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDef) Reset() {
	*x = ToolDef{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDef) ProtoMessage() {}

func (x *ToolDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDef.ProtoReflect.Descriptor instead.
func (*ToolDef) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDef) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

func (x *ToolDef) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *ToolDef) GetCacheControlJson() []byte {
	if x != nil {
		return x.CacheControlJson
	}
	return nil
}

// Canonical representation of a chat completion request.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolDef             `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Stream        bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float64               `protobuf:"fixed64,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP          *float64               `protobuf:"fixed64,7,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	StopSequences []string               `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Unparsed provider fields (passed transparently as JSON)
	ProviderExtensionsJson []byte `protobuf:"bytes,9,opt,name=provider_extensions_json,json=providerExtensionsJson,proto3" json:"provider_extensions_json,omitempty"`
	// Proxy-internal metadata shared between hooks. Not serialized to wire.
	ToranaMetaJson     []byte `protobuf:"bytes,10,opt,name=torana_meta_json,json=toranaMetaJson,proto3" json:"torana_meta_json,omitempty"`
	SafetySettingsJson []byte `protobuf:"bytes,11,opt,name=safety_settings_json,json=safetySettingsJson,proto3" json:"safety_settings_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTools() []*ToolDef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *ChatRequest) GetProviderExtensionsJson() []byte {
	if x != nil {
		return x.ProviderExtensionsJson
	}
	return nil
}

func (x *ChatRequest) GetToranaMetaJson() []byte {
	if x != nil {
		return x.ToranaMetaJson
	}
	return nil
}

func (x *ChatRequest) GetSafetySettingsJson() []byte {
	if x != nil {
		return x.SafetySettingsJson
	}
	return nil
}

type ToolCallStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque provider token on the call (Gemini thoughtSignature); empty otherwise.
	Signature     string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStart) Reset() {
	*x = ToolCallStart{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStart) ProtoMessage() {}

func (x *ToolCallStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStart.ProtoReflect.Descriptor instead.
func (*ToolCallStart) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallStart) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ToolCallDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ArgumentsDelta string                 `protobuf:"bytes,2,opt,name=arguments_delta,json=argumentsDelta,proto3" json:"arguments_delta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetArgumentsDelta() string {
	if x != nil {
		return x.ArgumentsDelta
	}
	return ""
}

type ToolCallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEnd) Reset() {
	*x = ToolCallEnd{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEnd) ProtoMessage() {}

func (x *ToolCallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEnd.ProtoReflect.Descriptor instead.
func (*ToolCallEnd) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCallEnd) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{7}
}

func (x *StreamError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamUsage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InputTokens  int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// Input tokens served from the provider's prompt cache.
	CacheReadTokens int32 `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	// Input tokens written to the cache this turn; 0 if unreported.
	CacheWriteTokens int32 `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamUsage) Reset() {
	*x = StreamUsage{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUsage) ProtoMessage() {}

func (x *StreamUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUsage.ProtoReflect.Descriptor instead.
func (*StreamUsage) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{8}
}

func (x *StreamUsage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *StreamUsage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *StreamUsage) GetCacheReadTokens() int32 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *StreamUsage) GetCacheWriteTokens() int32 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_TextDelta
	//	*StreamEvent_ThinkingDelta
	//	*StreamEvent_ToolCallStart
	//	*StreamEvent_ToolCallDelta
	//	*StreamEvent_ToolCallEnd
	//	*StreamEvent_FinishReason
	//	*StreamEvent_Usage
	//	*StreamEvent_Error
	//	*StreamEvent_SignatureDelta
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetTextDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetThinkingDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return ""
}

func (x *StreamEvent) GetToolCallStart() *ToolCallStart {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallStart); ok {
			return x.ToolCallStart
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetToolCallEnd() *ToolCallEnd {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ToolCallEnd); ok {
			return x.ToolCallEnd
		}
	}
	return nil
}

func (x *StreamEvent) GetFinishReason() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_FinishReason); ok {
			return x.FinishReason
		}
	}
	return ""
}

func (x *StreamEvent) GetUsage() *StreamUsage {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *StreamEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamEvent) GetSignatureDelta() string {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_SignatureDelta); ok {
			return x.SignatureDelta
		}
	}
	return ""
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_TextDelta struct {
	TextDelta string `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type StreamEvent_ThinkingDelta struct {
	ThinkingDelta string `protobuf:"bytes,2,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type StreamEvent_ToolCallStart struct {
	ToolCallStart *ToolCallStart `protobuf:"bytes,3,opt,name=tool_call_start,json=toolCallStart,proto3,oneof"`
}

type StreamEvent_ToolCallDelta struct {
	ToolCallDelta *ToolCallDelta `protobuf:"bytes,4,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type StreamEvent_ToolCallEnd struct {
	ToolCallEnd *ToolCallEnd `protobuf:"bytes,5,opt,name=tool_call_end,json=toolCallEnd,proto3,oneof"`
}

type StreamEvent_FinishReason struct {
	FinishReason string `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3,oneof"`
}

type StreamEvent_Usage struct {
	Usage *StreamUsage `protobuf:"bytes,7,opt,name=usage,proto3,oneof"`
}

type StreamEvent_Error struct {
	Error *StreamError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type StreamEvent_SignatureDelta struct {
	// Opaque provider signature paired with the surrounding block (Gemini
	// thoughtSignature on a standalone text/thought part).
	SignatureDelta string `protobuf:"bytes,9,opt,name=signature_delta,json=signatureDelta,proto3,oneof"`
}

func (*StreamEvent_TextDelta) isStreamEvent_Event() {}

func (*StreamEvent_ThinkingDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallStart) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallDelta) isStreamEvent_Event() {}

func (*StreamEvent_ToolCallEnd) isStreamEvent_Event() {}

func (*StreamEvent_FinishReason) isStreamEvent_Event() {}

func (*StreamEvent_Usage) isStreamEvent_Event() {}

func (*StreamEvent_Error) isStreamEvent_Event() {}

func (*StreamEvent_SignatureDelta) isStreamEvent_Event() {}

// Result of a run_on_stream_chunk hook invocation.
//
// A zero-length hook return means "not handled" — the input event passes
// through unchanged. A non-empty StreamEventResult with handled=true
// replaces the input event with `events`:
//
//	events empty  → suppress the input event
//	one event     → replace it
//	multiple      → fan-out (e.g. [ToolCallDelta(full args), ToolCallEnd])
//
// The explicit `handled` flag exists because an all-defaults protobuf
// message marshals to zero bytes — without it, "suppress" would be
// indistinguishable from "passthrough" on the wire.
type StreamEventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Events        []*StreamEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventResult) Reset() {
	*x = StreamEventResult{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventResult) ProtoMessage() {}

func (x *StreamEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventResult.ProtoReflect.Descriptor instead.
func (*StreamEventResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{10}
}

func (x *StreamEventResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *StreamEventResult) GetEvents() []*StreamEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Incoming HTTP request forwarded to a plugin's run_on_http_request hook.
// Built directly from net/http — does not cross the engine IR.
type HttpRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// JSON-encoded map of request headers (map[string][]string).
	HeadersJson   []byte `protobuf:"bytes,3,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{11}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Response produced by a plugin's run_on_http_request hook.
//
// The explicit `handled` bool is required: an all-defaults proto message
// marshals to zero bytes, which the host reads as "not handled". A plugin
// MUST set handled=true when it serves a response.
type HttpResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// JSON-encoded map of response headers (map[string][]string).
	HeadersJson   []byte `protobuf:"bytes,2,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Handled       bool   `protobuf:"varint,4,opt,name=handled,proto3" json:"handled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{12}
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeadersJson() []byte {
	if x != nil {
		return x.HeadersJson
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

// Fired periodically by the host, with no request in flight.
//
// Every other hook is reactive: a plugin can only act while a request is
// passing through it. This one exists so a plugin can act when nothing is
// happening — refreshing a provider cache before it lapses, emitting a periodic
// report, expiring its own state.
//
// The host attaches no meaning to a tick. It reports that time has passed and
// nothing else; what to do about it belongs entirely to the plugin.
//
// Requires the env.background_tick permission. Running code with no request in
// flight is a capability an operator should grant deliberately, and a plugin
// that holds it can act — and spend — outside any request the operator can see.
type TickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing per host process, starting at 1. Useful for
	// "every Nth tick" without the plugin keeping its own counter.
	TickId uint64 `protobuf:"varint,1,opt,name=tick_id,json=tickId,proto3" json:"tick_id,omitempty"`
	// Host wall-clock time. Plugins have no clock of their own: WASI preview1
	// exposes none, and this is the only time source they get.
	UnixMillis int64 `protobuf:"varint,2,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	// Configured interval, so a plugin can reason about elapsed time without
	// assuming a particular cadence.
	IntervalMs    int64 `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickRequest) Reset() {
	*x = TickRequest{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickRequest) ProtoMessage() {}

func (x *TickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickRequest.ProtoReflect.Descriptor instead.
func (*TickRequest) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{13}
}

func (x *TickRequest) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

func (x *TickRequest) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *TickRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// Result of a run_on_tick invocation.
//
// The explicit `handled` flag is required for the same reason as
// StreamEventResult and HttpResponse: an all-defaults protobuf message
// marshals to zero bytes, which the host reads as "did nothing". Without it a
// plugin that acted but reported nothing would be indistinguishable from one
// that never ran.
type TickResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Handled bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	// How many actions the plugin took this tick. Surfaced in /stats so an
	// operator can see background work happening without reading logs.
	Actions int32 `protobuf:"varint,2,opt,name=actions,proto3" json:"actions,omitempty"`
	// Short human-readable status for the control plane, e.g. "refreshed 2 of 3
	// conversations". Not for error reporting — a failing hook should trap.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickResult) Reset() {
	*x = TickResult{}
	mi := &file_proto_torana_v1_torana_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickResult) ProtoMessage() {}

func (x *TickResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torana_v1_torana_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickResult.ProtoReflect.Descriptor instead.
func (*TickResult) Descriptor() ([]byte, []int) {
	return file_proto_torana_v1_torana_proto_rawDescGZIP(), []int{14}
}

func (x *TickResult) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *TickResult) GetActions() int32 {
	if x != nil {
		return x.Actions
	}
	return 0
}

func (x *TickResult) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_proto_torana_v1_torana_proto protoreflect.FileDescriptor

const file_proto_torana_v1_torana_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/torana/v1/torana.proto\x12\ttorana.v1\"\xfe\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x12content_parts_json\x18\x03 \x01(\fR\x10contentPartsJson\x12\x1a\n" +
	"\bthinking\x18\x04 \x01(\tR\bthinking\x12-\n" +
	"\x12thinking_signature\x18\x05 \x01(\tR\x11thinkingSignature\x12+\n" +
	"\x11redacted_thinking\x18\t \x01(\tR\x10redactedThinking\x122\n" +
	"\n" +
	"tool_calls\x18\x06 \x03(\v2\x13.torana.v1.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\a \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\b \x01(\tR\btoolName\x12,\n" +
	"\x12cache_control_json\x18\n" +
	" \x01(\fR\x10cacheControlJson\"s\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xae\x01\n" +
	"\aToolDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\fR\x0eparametersJson\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\x12,\n" +
	"\x12cache_control_json\x18\x05 \x01(\fR\x10cacheControlJson\"\xe0\x03\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12.\n" +
	"\bmessages\x18\x02 \x03(\v2\x12.torana.v1.MessageR\bmessages\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.torana.v1.ToolDefR\x05tools\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\"\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x01H\x01R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\a \x01(\x01H\x02R\x04topP\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x128\n" +
	"\x18provider_extensions_json\x18\t \x01(\fR\x16providerExtensionsJson\x12(\n" +
	"\x10torana_meta_json\x18\n" +
	" \x01(\fR\x0etoranaMetaJson\x120\n" +
	"\x14safety_settings_json\x18\v \x01(\fR\x12safetySettingsJsonB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_p\"g\n" +
	"\rToolCallStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"N\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12'\n" +
	"\x0farguments_delta\x18\x02 \x01(\tR\x0eargumentsDelta\"#\n" +
	"\vToolCallEnd\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\";\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\vStreamUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x05R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x05R\x10cacheWriteTokens\"\xd8\x03\n" +
	"\vStreamEvent\x12\x1f\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tH\x00R\ttextDelta\x12'\n" +
	"\x0ethinking_delta\x18\x02 \x01(\tH\x00R\rthinkingDelta\x12B\n" +
	"\x0ftool_call_start\x18\x03 \x01(\v2\x18.torana.v1.ToolCallStartH\x00R\rtoolCallStart\x12B\n" +
	"\x0ftool_call_delta\x18\x04 \x01(\v2\x18.torana.v1.ToolCallDeltaH\x00R\rtoolCallDelta\x12<\n" +
	"\rtool_call_end\x18\x05 \x01(\v2\x16.torana.v1.ToolCallEndH\x00R\vtoolCallEnd\x12%\n" +
	"\rfinish_reason\x18\x06 \x01(\tH\x00R\ffinishReason\x12.\n" +
	"\x05usage\x18\a \x01(\v2\x16.torana.v1.StreamUsageH\x00R\x05usage\x12.\n" +
	"\x05error\x18\b \x01(\v2\x16.torana.v1.StreamErrorH\x00R\x05error\x12)\n" +
	"\x0fsignature_delta\x18\t \x01(\tH\x00R\x0esignatureDeltaB\a\n" +
	"\x05event\"]\n" +
	"\x11StreamEventResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12.\n" +
	"\x06events\x18\x02 \x03(\v2\x16.torana.v1.StreamEventR\x06events\"p\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fheaders_json\x18\x03 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"w\n" +
	"\fHttpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12!\n" +
	"\fheaders_json\x18\x02 \x01(\fR\vheadersJson\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x18\n" +
	"\ahandled\x18\x04 \x01(\bR\ahandled\"h\n" +
	"\vTickRequest\x12\x17\n" +
	"\atick_id\x18\x01 \x01(\x04R\x06tickId\x12\x1f\n" +
	"\vunix_millis\x18\x02 \x01(\x03R\n" +
	"unixMillis\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x03R\n" +
	"intervalMs\"T\n" +
	"\n" +
	"TickResult\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x18\n" +
	"\aactions\x18\x02 \x01(\x05R\aactions\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04noteB-Z+github.com/torana-edge/torana-plugin-sdk/pbb\x06proto3"

var (
	file_proto_torana_v1_torana_proto_rawDescOnce sync.Once
	file_proto_torana_v1_torana_proto_rawDescData []byte
)

func file_proto_torana_v1_torana_proto_rawDescGZIP() []byte {
	file_proto_torana_v1_torana_proto_rawDescOnce.Do(func() {
		file_proto_torana_v1_torana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torana_v1_torana_proto_rawDesc), len(file_proto_torana_v1_torana_proto_rawDesc)))
	})
	return file_proto_torana_v1_torana_proto_rawDescData
}

var file_proto_torana_v1_torana_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_torana_v1_torana_proto_goTypes = []any{
	(*Message)(nil),           // 0: torana.v1.Message
	(*ToolCall)(nil),          // 1: torana.v1.ToolCall
	(*ToolDef)(nil),           // 2: torana.v1.ToolDef
	(*ChatRequest)(nil),       // 3: torana.v1.ChatRequest
	(*ToolCallStart)(nil),     // 4: torana.v1.ToolCallStart
	(*ToolCallDelta)(nil),     // 5: torana.v1.ToolCallDelta
	(*ToolCallEnd)(nil),       // 6: torana.v1.ToolCallEnd
	(*StreamError)(nil),       // 7: torana.v1.StreamError
	(*StreamUsage)(nil),       // 8: torana.v1.StreamUsage
	(*StreamEvent)(nil),       // 9: torana.v1.StreamEvent
	(*StreamEventResult)(nil), // 10: torana.v1.StreamEventResult
	(*HttpRequest)(nil),       // 11: torana.v1.HttpRequest
	(*HttpResponse)(nil),      // 12: torana.v1.HttpResponse
	(*TickRequest)(nil),       // 13: torana.v1.TickRequest
	(*TickResult)(nil),        // 14: torana.v1.TickResult
}
var file_proto_torana_v1_torana_proto_depIdxs = []int32{
	1, // 0: torana.v1.Message.tool_calls:type_name -> torana.v1.ToolCall
	0, // 1: torana.v1.ChatRequest.messages:type_name -> torana.v1.Message
	2, // 2: torana.v1.ChatRequest.tools:type_name -> torana.v1.ToolDef
	4, // 3: torana.v1.StreamEvent.tool_call_start:type_name -> torana.v1.ToolCallStart
	5, // 4: torana.v1.StreamEvent.tool_call_delta:type_name -> torana.v1.ToolCallDelta
	6, // 5: torana.v1.StreamEvent.tool_call_end:type_name -> torana.v1.ToolCallEnd
	8, // 6: torana.v1.StreamEvent.usage:type_name -> torana.v1.StreamUsage
	7, // 7: torana.v1.StreamEvent.error:type_name -> torana.v1.StreamError
	9, // 8: torana.v1.StreamEventResult.events:type_name -> torana.v1.StreamEvent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_torana_v1_torana_proto_init() }
func file_proto_torana_v1_torana_proto_init() {
	if File_proto_torana_v1_torana_proto != nil {
		return
	}
	file_proto_torana_v1_torana_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_torana_v1_torana_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamEvent_TextDelta)(nil),
		(*StreamEvent_ThinkingDelta)(nil),
		(*StreamEvent_ToolCallStart)(nil),
		(*StreamEvent_ToolCallDelta)(nil),
		(*StreamEvent_ToolCallEnd)(nil),
		(*StreamEvent_FinishReason)(nil),
		(*StreamEvent_Usage)(nil),
		(*StreamEvent_Error)(nil),
		(*StreamEvent_SignatureDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torana_v1_torana_proto_rawDesc), len(file_proto_torana_v1_torana_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_torana_v1_torana_proto_goTypes,
		DependencyIndexes: file_proto_torana_v1_torana_proto_depIdxs,
		MessageInfos:      file_proto_torana_v1_torana_proto_msgTypes,
	}.Build()
	File_proto_torana_v1_torana_proto = out.File
	file_proto_torana_v1_torana_proto_goTypes = nil
	file_proto_torana_v1_torana_proto_depIdxs = nil
}
